// AUTO-GENERATED by scripts/cut_monsta_sheet.py — do not edit by hand.
// Re-run `py scripts/cut_monsta_sheet.py` and this is rewritten with the art.

/**
 * Cache-bust for every can PNG and FX layer (foodArt / canFxArt in foodMeta):
 * a hash of the pixels the cut wrote, so it changes exactly when they do. The
 * service worker serves images stale-while-revalidate, so new art under an old
 * ?v= would keep showing on phones.
 */
export const CAN_ART_V = 'bb5f9384'

/** Where every FX layer sits: a 1.5x box centred on the can's square art box. */
export const CAN_FX_BOX = { left: '-25%', top: '-25%', width: '150%', height: '150%' } as const

export interface CanFxLayerData {
  /** File name in public/food/fx, without the extension. */
  name: string
  kind: 'sparkle' | 'ray'
  /** transform-origin, % of the layer box: a sparkle's own centre, or the
   *  rays' shared radial centre, so a scale pulses in place or pushes outward. */
  origin: readonly [number, number]
}

/** The moving layers of each can that has them, in the order they are drawn. */
export const CAN_FX_LAYERS: Partial<Record<string, readonly CanFxLayerData[]>> = {
  monsta_rainbow: [
    { name: 'monsta_rainbow_sparkle_1', kind: 'sparkle', origin: [33.243, 32.314] },
    { name: 'monsta_rainbow_sparkle_2', kind: 'sparkle', origin: [35.743, 23.117] },
    { name: 'monsta_rainbow_sparkle_3', kind: 'sparkle', origin: [62.75, 19.529] },
    { name: 'monsta_rainbow_sparkle_4', kind: 'sparkle', origin: [65.678, 26.498] },
    { name: 'monsta_rainbow_sparkle_5', kind: 'sparkle', origin: [65.842, 34.707] },
  ],
  monsta_gold: [
    { name: 'monsta_gold_rays_a', kind: 'ray', origin: [50, 45.379] },
    { name: 'monsta_gold_rays_b', kind: 'ray', origin: [50, 45.379] },
  ],
}
