// GENERATED by scripts/anim_manifest.py from public/anim/*.json -- do not edit.
//
// Baked sprite-animation frame strips for Eren. Each entry describes ONE strip:
// a single row of `frames` equal-sized frames, frame 0 (the resting pose)
// first. SpriteStrip plays it by sliding the row with steps(frames), so the
// sprite animates on real drawn frames instead of a CSS transform on a flat
// PNG.
//
// `rect` is the strip's placement inside the FULL sprite canvas, in percent, so
// an overlay layer (the tail behind the body, the eye band over it) lands
// exactly on the body PNG with no letterbox math. A full-canvas animation (the
// eat poses) is 0/0/100/100.

export interface ErenAnim {
  /** Manifest key, e.g. 'cookTail'. */
  name: string
  /** Public path of the 1-row strip. */
  src: string
  /** Frame count; also the steps() count. */
  frames: number
  /** Full loop length in ms. */
  durationMs: number
  /** 'loop' plays every frame evenly; 'blink' holds frame 0 and flicks. */
  kind: 'loop' | 'blink'
  /** One frame's pixel size inside the strip. */
  frameW: number
  frameH: number
  /** The full sprite canvas [w, h] that `rect` is measured against. */
  canvas: readonly [number, number]
  /** Placement inside that canvas, in percent. */
  rect: { left: number; top: number; width: number; height: number }
  /** The sprite PNG this layer composites over, when it is an overlay. */
  bodySrc: string | null
  /** What the baker did, for whoever reads this next. */
  note: string
}

export const EREN_ANIM = {
  cookBlink: {
    name: 'cookBlink',
    src: '/anim/cook_blink.webp',
    frames: 3,
    durationMs: 6000,
    kind: 'blink',
    frameW: 376,
    frameH: 152,
    canvas: [959, 1536],
    rect: { left: 31.2826, top: 34.5052, width: 39.2075, height: 9.8958 },
    bodySrc: '/ErenCook_notail.png',
    note: 'Eyelid-only overlay: alpha is cut to the two sockets, and frame 0 is fully transparent because the body PNG already draws the open eyes. The socket fills with its own fur and the eye closes onto its own drawn bottom edge, two blocks of the art grid thick. Composite over the body PNG at rect.',
  },
  cookTail: {
    name: 'cookTail',
    src: '/anim/cook_tail.webp',
    frames: 24,
    durationMs: 3400,
    kind: 'loop',
    frameW: 142,
    frameH: 280,
    canvas: [959, 1536],
    rect: { left: 70.4901, top: 48.5026, width: 29.5099, height: 36.4583 },
    bodySrc: '/ErenCook_notail.png',
    note: 'Tail bends instead of swinging: root glued, curvature accumulates to the tip, tip lags 476ms and follows through. Baked rhythm runs +7.6% late vs @keyframes erenTailWiggle (tip peaks at 47.6% of the loop, not 40%) because the per-row time remap squeezes the sway into 84% of the cycle. Harmless alone; do not show this against a flat-PNG cat still running the CSS rotation, or the two will beat.',
  },
  eat1: {
    name: 'eat1',
    src: '/anim/eat1_chew.webp',
    frames: 6,
    durationMs: 440,
    kind: 'loop',
    frameW: 462,
    frameH: 382,
    canvas: [925, 765],
    rect: { left: 0.0, top: 0.0, width: 100.0, height: 100.0 },
    bodySrc: null,
    note: 'Chew: the head presses onto a pinned contact line and the snout absorbs it. Rigid from the crown to the iris bottom, so the eyes travel with the skull (2.05 CSS px at 140 wide) and never deform -- iris strain is 0.00% on every frame. The muzzle then pumps on the jaw clock inside its own column window between the paws: the nose travels 0.65 CSS px and the chin with it, while the paws and the tail hold still. Lossy VP8, so the contact band is NOT byte-identical: it decodes within 40/255 of the source and moves at most 24/255 between frames.',
  },
  eat2: {
    name: 'eat2',
    src: '/anim/eat2_chew.webp',
    frames: 6,
    durationMs: 440,
    kind: 'loop',
    frameW: 454,
    frameH: 438,
    canvas: [907, 877],
    rect: { left: 0.0, top: 0.0, width: 100.0, height: 100.0 },
    bodySrc: null,
    note: 'Chew: the head presses onto a pinned contact line and the snout absorbs it. Rigid from the crown to the iris bottom, so the eyes travel with the skull (1.54 CSS px at 140 wide) and never deform -- iris strain is 0.00% on every frame. The muzzle then pumps on the jaw clock inside its own column window between the paws: the nose travels 0.65 CSS px and the chin with it, while the paws and the tail hold still. Lossy VP8, so the contact band is NOT byte-identical: it decodes within 40/255 of the source and moves at most 24/255 between frames.',
  },
  eat3: {
    name: 'eat3',
    src: '/anim/eat3_chew.webp',
    frames: 6,
    durationMs: 440,
    kind: 'loop',
    frameW: 424,
    frameH: 398,
    canvas: [848, 796],
    rect: { left: 0.0, top: 0.0, width: 100.0, height: 100.0 },
    bodySrc: null,
    note: 'Chew: the head presses onto a pinned contact line and the snout absorbs it. Rigid from the crown to the iris bottom, so the eyes travel with the skull (2.05 CSS px at 140 wide) and never deform -- iris strain is 0.00% on every frame. The muzzle then pumps on the jaw clock inside its own column window between the paws: the nose travels 0.65 CSS px and the chin with it, while the paws and the tail hold still. Lossy VP8, so the contact band is NOT byte-identical: it decodes within 40/255 of the source and moves at most 24/255 between frames.',
  },
  eat4: {
    name: 'eat4',
    src: '/anim/eat4_chew.webp',
    frames: 6,
    durationMs: 440,
    kind: 'loop',
    frameW: 470,
    frameH: 454,
    canvas: [940, 908],
    rect: { left: 0.0, top: 0.0, width: 100.0, height: 100.0 },
    bodySrc: null,
    note: 'Chew: the head presses onto a pinned contact line and the snout absorbs it. Rigid from the crown to the iris bottom, so the eyes travel with the skull (1.75 CSS px at 140 wide) and never deform -- iris strain is 0.00% on every frame. The muzzle then pumps on the jaw clock inside its own column window between the paws: the nose travels 0.45 CSS px and the chin with it, while the paws and the tail hold still. Lossy VP8, so the contact band is NOT byte-identical: it decodes within 40/255 of the source and moves at most 24/255 between frames.',
  },
} as const satisfies Record<string, ErenAnim>

export type ErenAnimKey = keyof typeof EREN_ANIM
