// AUTO-GENERATED by scripts/build_window_frames.py - do not edit by hand.
//
// Where each room's window is, and the cut-out that draws its frame back
// over the weather. `box` is in fractions of the ROOM ART, which is the
// space RoomWeather positions in (inside a cover box that mirrors the
// picture's own aspect ratio).
//
// A room whose night art is a different picture carries a second cut; one
// already painted after dark (the bedroom) points `night` back at its day
// cut. `night: null` means no clean cut of that room after dark exists, so
// it simply has no weather then -- an absence beats a leak.

export interface RoomWindow {
  /** For the picker in the Lab. */
  label: string
  /** Source art size, so the cover box can reproduce `background-size: cover`. */
  art: { w: number; h: number }
  /** Window aperture, as fractions of the art. */
  box: { l: number; t: number; w: number; h: number }
  /** The frame cut, drawn over the weather. */
  day: string
  /** null = this room has no clean cut of its night art, so no weather then. */
  night: string | null
}

export const ROOM_WINDOWS: Record<string, RoomWindow> = {
  home: {
    label: 'LIVING ROOM',
    art: { w: 768, h: 1376 },
    box: { l: 0.47396, t: 0.10538, w: 0.45313, h: 0.29433 },
    day: '/weather/home.png?v=2',
    night: '/weather/home_night.png?v=2',
  },
  feed: {
    label: 'KITCHEN',
    art: { w: 768, h: 1376 },
    box: { l: 0.322, t: 0.283, w: 0.342, h: 0.222 },
    day: '/weather/feed.png?v=2',
    night: '/weather/feed_night.png?v=2',
  },
  play: {
    label: 'PLAYROOM',
    art: { w: 768, h: 1376 },
    box: { l: 0.8386, t: 0.1963, w: 0.15625, h: 0.306 },
    day: '/weather/play.png?v=2',
    night: '/weather/play_night.png?v=2',
  },
  sleep: {
    label: 'BEDROOM',
    art: { w: 768, h: 1376 },
    box: { l: 0.29297, t: 0.17224, w: 0.38412, h: 0.37282 },
    day: '/weather/sleep.png?v=2',
    night: '/weather/sleep.png?v=2',
  },
  wash: {
    label: 'BATHROOM',
    art: { w: 768, h: 1376 },
    box: { l: 0.755208, t: 0.164244, w: 0.179688, h: 0.175872 },
    day: '/weather/wash.png?v=2',
    night: '/weather/wash_night.png?v=2',
  },
  chemistry: {
    label: 'LAB',
    art: { w: 941, h: 1672 },
    box: { l: 0.37, t: 0.115, w: 0.285, h: 0.275 },
    day: '/weather/chemistry.png?v=2',
    night: '/weather/chemistry_night.png?v=2',
  },
  talk: {
    label: 'ATTIC',
    art: { w: 941, h: 1672 },
    box: { l: 0.792, t: 0.205, w: 0.18, h: 0.14 },
    day: '/weather/talk.png?v=2',
    night: '/weather/talk_night.png?v=2',
  },
}

/** Every room the weather machine can set, in swipe order. */
export const WEATHER_ROOMS: { room: string; label: string }[] =
  Object.entries(ROOM_WINDOWS).map(([room, w]) => ({ room, label: w.label }))
