import { canFxArt } from '@/lib/foodMeta'
import { CAN_FX_BOX, CAN_FX_LAYERS } from '@/lib/canArtData'

// ═══════════════════════════════════════════════════════════════════════════
// CAN FX: the moving parts of the two SPECIAL EDITION cans.
//
// In the owner's drawing the Rainbow can has five sparkles floating around it
// and the Gold can has eight ray dashes. scripts/cut_monsta_sheet.py cuts those
// out as their own PNGs (public/food/fx) so they can move while the can stays
// still. Each layer is a 1.5x canvas in the can's own frame and scale, centred
// on the can canvas. That makes the geometry the same at every size: -25% /
// -25% / 150% / 150% of the square the can art fills. The box and each layer's
// transform-origin are generated by the cut into lib/canArtData.ts, so a re-cut
// can't leave them stale.
//
// The motion is subtle on purpose. The owner asked for the art not to look
// stiff, not for a light show:
//  - each sparkle twinkles on its own period, so they never pulse together
//  - the two ray sets take turns glinting outward and blinking off
// Both use stepped keyframes (canFxTwinkle / canFxRays in globals.css), and the
// travel is in % so it scales with the art. With reduced motion the layers
// hold still and fully visible, exactly as drawn.
//
// Render it inside a position:relative box that is exactly the can's square
// art box. FoodIcon, the gacha reveal and the collection all do this.
// ═══════════════════════════════════════════════════════════════════════════

// Timing is the one thing chosen here; where each layer sits comes from the
// cut (canArtData). Sparkles are numbered left to right: 1 big purple (left),
// 2 yellow, 3 small purple (top right), 4 pink, 5 blue. The phases space out
// the first round so they twinkle left, right, left, right (1, 3, 2, 5, 4),
// about 0.7s apart; after that the different periods keep the order changing.
// rays_a is the 1st and 3rd ray from the top on each side, rays_b the 2nd and
// 4th; half a period apart, so the two sets take turns.
const TIMING: Record<string, { period: number; phase: number }> = {
  monsta_rainbow_sparkle_1: { period: 3.3, phase: 1.55 },
  monsta_rainbow_sparkle_2: { period: 4.1, phase: 0.6 },
  monsta_rainbow_sparkle_3: { period: 3.7, phase: 1.07 },
  monsta_rainbow_sparkle_4: { period: 4.5, phase: 4.02 },
  monsta_rainbow_sparkle_5: { period: 3.0, phase: 2.28 },
  monsta_gold_rays_a:       { period: 3.4, phase: 0 },
  monsta_gold_rays_b:       { period: 3.4, phase: 1.7 },
}

/** True for the cans whose art comes with separate moving FX layers. */
export const hasCanFx = (foodId: string): boolean => !!CAN_FX_LAYERS[foodId]

export default function CanFx({ id }: { id: string }) {
  const layers = CAN_FX_LAYERS[id]
  if (!layers) return null

  return (
    <span aria-hidden className="absolute inset-0 pointer-events-none" style={{ overflow: 'visible' }}>
      {layers.map(l => {
        const t = TIMING[l.name] ?? { period: 3.6, phase: 0 }
        return (
          <img key={l.name} src={canFxArt(l.name)} alt="" draggable={false}
            className={l.kind === 'sparkle' ? 'canfx-sparkle' : 'canfx-ray'}
            style={{
              position: 'absolute', ...CAN_FX_BOX,
              // Tailwind's preflight caps every img at max-width 100%, which
              // would quietly shrink the 150% layer back to the can's box.
              maxWidth: 'none',
              transformOrigin: `${l.origin[0]}% ${l.origin[1]}%`,
              animationDuration: `${t.period}s`,
              animationDelay: `-${t.phase}s`,
            }} />
        )
      })}
    </span>
  )
}
