'use client'

import { useState, useRef, useCallback, useEffect, useMemo } from 'react'
import { useAuth } from '@/hooks/useAuth'
import { useErenStats, getCachedIsSleeping } from '@/hooks/useErenStats'
import { useTasks } from '@/contexts/TaskContext'
import { cn } from '@/lib/utils'
import BlinkingEren from '@/components/BlinkingEren'
import { useRoomEren } from '@/hooks/useRoomEren'
import ErenIdleLayer from '@/components/ErenIdleLayer'
import StinkyFlies from '@/components/StinkyFlies'
import LightSwitch from '@/components/LightSwitch'
import { useIsDark } from '@/hooks/useIsDark'
import { useWish } from '@/contexts/WishContext'
import WishHintBanner from '@/components/wish/WishHintBanner'
import { wishHintRoom } from '@/lib/wishes'
import { playSound, playLoop } from '@/lib/sounds'
import { useErenReaction } from '@/hooks/useErenReaction'
import { happyFinisherBeats, WORD_COLOR } from '@/lib/erenReactions'
import SoundWord from '@/components/SoundWord'
import { Droplets, Sparkles, Hearts } from '@/components/care/ReactionFx'
import PoseSprite from '@/components/care/PoseSprite'
import { BubblePoof, SplashPoof, WASH_POOF_PEAK_MS } from '@/components/care/WashPoof'
import { preloadImages } from '@/lib/preloadImages'
import SqueakyCleanBanner from '@/components/wash/SqueakyCleanBanner'
import SegmentMeter, { type MeterPalette } from '@/components/care/SegmentMeter'

interface Props { onClose: () => void }

// Premium gauge palettes for the SOAP (warm pink lather) and RINSE (cool sky
// water) meters. They sit inside the dark navy bath panel, so the channel ink
// is a deep navy and the studs are the app's signature gold rivets.
const SOAP_METER: MeterPalette = {
  fillHi: '#FFC7DE', fillBase: '#FF6B9D', fillLo: '#E0487E', fillEdge: '#FF4080',
  glow: 'rgba(255,90,150,0.65)', track: '#22323F', trackEdge: '#37495A',
  groove: '#0E1C28', frame: '#27485C', rivet: '#FFD98A',
}
const RINSE_METER: MeterPalette = {
  fillHi: '#D4F0FF', fillBase: '#6BAED6', fillLo: '#3F86B4', fillEdge: '#4A90BC',
  glow: 'rgba(105,174,214,0.7)', track: '#22323F', trackEdge: '#37495A',
  groove: '#0E1C28', frame: '#27485C', rivet: '#FFD98A',
}

// ── Soap-coverage → pose progression ─────────────────────────────────────────
// He swaps through lather stages as `coverage` climbs (soaping) and back down
// (rinsing), then a wet pose for the finishing shake. 'stand' = the everyday
// standing sprite. Bubble poof masks each step UP, water-splash poof each DOWN.
type WashStage = 'stand' | 's1' | 's2' | 's3' | 'wet'
const WASH_POSE_SRC: Record<Exclude<WashStage, 'stand'>, string> = {
  s1:  '/erenWash1.png?v=1',
  s2:  '/erenWash2.png?v=1',
  s3:  '/erenWash3.png?v=1',
  wet: '/erenWashWet.png?v=1',
}
const STAGE_RANK: Record<string, number> = { stand: 0, s1: 1, s2: 2, s3: 3 }
function poofTypeFor(prev: WashStage, next: WashStage): 'bubble' | 'water' {
  // Soaping UP between lather stages bubbles; everything else (rinsing down,
  // entering/leaving the wet pose) splashes.
  if (prev in STAGE_RANK && next in STAGE_RANK) return STAGE_RANK[next] > STAGE_RANK[prev] ? 'bubble' : 'water'
  return 'water'
}

// A quick wet-dog shake fired imperatively (WAAPI) on every RINSE transition, so
// each time the water sprays off him he visibly shakes it away. Pivots at the
// feet (transform-origin set on the wrapper); amplitude decays like a real
// shake. Kept off the big finish shake (which has its own erenShakeDry).
const WASH_SHAKE_KEYFRAMES: Keyframe[] = [
  { transform: 'rotate(0deg)' },
  { transform: 'rotate(-6deg)' },
  { transform: 'rotate(5deg)' },
  { transform: 'rotate(-4deg)' },
  { transform: 'rotate(2.5deg)' },
  { transform: 'rotate(-1deg)' },
  { transform: 'rotate(0deg)' },
]
const WASH_SHAKE_TIMING: KeyframeAnimationOptions = { duration: 480, easing: 'linear' }
// `c` = coverage % at the time this bubble was created. Used to fade
// each bubble out individually as the rinse progresses past its
// creation moment (newest/topmost bubbles wash off first).
interface Bubble { id: number; x: number; y: number; size: number; c: number }

// Eren's silhouette in the bathroom (ErenBathroomHat pose) as a 24×24
// occupancy grid over his 200px sprite box: '1' = a cell his body/hat/tail
// covers. Generated by scripts/measure_bath_mask.js from the sprite's alpha,
// then the two interior gaps (between the ear tips, row 3, and between the
// front paws, row 21) were filled by hand so a continuous scrub across his
// head or feet doesn't stutter. Used to confine soap suds to his body so
// nothing lands on the floor, walls, or the empty corners of his box.
const EREN_MASK = [
  '000000000000000000000000',
  '000000000000000000000000',
  '000000000000000000000000',
  '000000111111111000000000',
  '000001111111111100000000',
  '000001111111111100000000',
  '000001111111111100000000',
  '000000111111111000000000',
  '000001111111111100000000',
  '000001111111111100000000',
  '000001111111111100000000',
  '000001111111111110000000',
  '000000111111111111000000',
  '000000111111111111000000',
  '000000111111111111000000',
  '000001111111111111000000',
  '000001111111111111000000',
  '000001111111111111000000',
  '000000111111111110000000',
  '000000111111111100000000',
  '000000011111111000000000',
  '000000001111100000000000',
  '000000000000000000000000',
  '000000000000000000000000',
]
const MASK_COLS = 24
const MASK_ROWS = 24

// ── Prop sprites (Shower.png / Soap.png) ─────────────────────────────────────
// The shower is a tall handheld head: its perforated spray PLATE sits on the
// upper-left of the head and its face aims down-left. So the water emitter is
// pinned to that plate (as a % of the sprite box) and the spray fans down-left
// to match where the plate actually points — not straight down from the body.
const SHOWER_W = 40                                  // px display width
const SHOWER_H = Math.round(SHOWER_W * 240 / 88)     // cleaned sprite is 88×240
const DISC_X   = 15                                  // % of sprite box — plate face
const DISC_Y   = 18
const SPRAY_RAYS = [12, 22, 31, 40, 49]              // deg clockwise → down-left fan
const SOAP_W   = 54                                  // px display width
const SOAP_H   = Math.round(SOAP_W * 177 / 240)      // cleaned sprite is 240×177

// Bathroom idle look (ErenBathroomHat) — default when no Closet skin is set.
const WASH_EREN_FALLBACK = {
  src: '/ErenBathroomHat_notail.png', tailSrc: '/ErenBathroomHat_tail.png', tailOrigin: '65.9% 77.6%',
  eyes: {
    lidTop: '36.34%', lidWidth: '5.4%', lidLeftA: '34.38%', lidLeftB: '48.21%',
    maskTop: '36.34%', maskLeftA: '34.38%', maskLeftB: '48.21%', maskW: '5.4%', maskH: '4.36%',
    glintLeftA: '59%', glintTopA: '2%', glintLeftB: '20%', glintTopB: '2%', glintW: '22%',
  },
}

export default function WashScene({ onClose }: Props) {
  const { user, profile } = useAuth()
  const { stats, applyAction } = useErenStats(profile?.household_id ?? null)
  const { completeTask } = useTasks()
  const wish = useWish()
  const wishMatchesThisRoom = wish?.wish ? wishHintRoom(wish.wish) === 'wash' : false

  const sceneRef   = useRef<HTMLDivElement>(null)
  const soapRef    = useRef<HTMLDivElement>(null)
  const showerRef  = useRef<HTMLDivElement>(null)
  const erenRef    = useRef<HTMLDivElement>(null)

  // Positions stored in refs — updated directly on DOM, no re-render
  const soapPosRef   = useRef({ x: 12, y: 62 })
  const showerPosRef = useRef({ x: 75, y: 30 })

  const [dragSoap,   setDragSoap]   = useState(false)
  const [dragShower, setDragShower] = useState(false)
  const [coverage,   setCoverage]   = useState(0)
  const [bubbles,    setBubbles]    = useState<Bubble[]>([])
  const [showShower, setShowShower] = useState(false)
  const [done,       setDone]       = useState(false)
  const [saving,     setSaving]     = useState(false)
  const [toast,      setToast]      = useState<string | null>(null)

  const bubbleId      = useRef(0)
  const dragSoapRef   = useRef(false)
  const dragShowerRef = useRef(false)
  const doneRef       = useRef(false)
  const showShowerRef = useRef(false)
  const coverageRef   = useRef(0)

  const cleanliness = stats?.cleanliness ?? 100
  const isDark = useIsDark()
  // Cache fallback so Eren renders synchronously with the right state.
  const isSleeping = stats?.is_sleeping ?? getCachedIsSleeping() ?? true

  // Reaction runner — squirm while being soaped, shake-dry + sparkle on finish.
  const reaction = useErenReaction()
  const [scrubbing, setScrubbing] = useState(false)
  const scrubStopRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  // Mark "being scrubbed" on each in-zone soap move; auto-clear ~250ms after
  // the last one so a continuous scrub holds the squirm but pausing stops it.
  const markScrub = useCallback(() => {
    setScrubbing(true)
    if (scrubStopRef.current) clearTimeout(scrubStopRef.current)
    scrubStopRef.current = setTimeout(() => setScrubbing(false), 250)
  }, [])
  useEffect(() => () => { if (scrubStopRef.current) clearTimeout(scrubStopRef.current) }, [])
  // Throttle the "SCRUB SCRUB" word so it pops at most ~once/1.2s while soaping.
  const lastScrubWordRef = useRef(0)
  const [scrubWordKey, setScrubWordKey] = useState(0)

  // Loop the recorded soap mp3 while actively soaping. The 2s clip can't be
  // re-triggered per pointermove without stacking overlapping copies, so we run
  // a single looping source while `scrubbing` holds — each in-zone rub keeps it
  // alive and a ~250ms pause stops it with a short fade.
  useEffect(() => {
    if (!scrubbing) return
    return playLoop('care_soap')
  }, [scrubbing])

  // Loop the rinse mp3 for the WHOLE time the showerhead is held — keyed to
  // `dragShower`, NOT pointer movement, so holding the shower steady over him
  // keeps a seamless continuous stream (Web Audio loops the gapless 1s clip
  // sample-accurately). It stops, with a short fade, only when he's released —
  // matching the falling-water droplets, which also render while `dragShower`.
  useEffect(() => {
    if (!dragShower) return
    return playLoop('care_rinse')
  }, [dragShower])

  // ── Pose progression driven by soap coverage ──────────────────────────────
  const [visibleStage, setVisibleStage] = useState<WashStage>('stand')
  const [washStarted,  setWashStarted]  = useState(false)
  const [poof, setPoof] = useState<{ type: 'bubble' | 'water'; key: number } | null>(null)
  const prevStageRef = useRef<WashStage>('stand')
  const poofKeyRef   = useRef(0)
  // Wraps the visible sprite/pose; a rinse transition triggers a shake on it.
  const washShakeRef = useRef<HTMLDivElement>(null)

  // Preload the lather/wet stickers so the first swap doesn't flash.
  useEffect(() => {
    preloadImages(['/erenWash1.png?v=1', '/erenWash2.png?v=1', '/erenWash3.png?v=1', '/erenWashWet.png?v=1', '/shower.png?v=1', '/soap.png?v=1'])
  }, [])

  // Once soaping has begun we never drop back to the dry standing pose until the
  // finishing shake — rinsing down to 0% keeps a light lather, not a dry cat.
  useEffect(() => {
    if (coverage >= 8 && !washStarted) setWashStarted(true)
  }, [coverage, washStarted])

  // The stage we SHOULD be at right now. During the finish sequence he's the
  // wet pose through the shake, then back to standing for the happy hop.
  const targetStage: WashStage = done
    ? (reaction.phase === 'shake' || reaction.phase === 'sparkle' ? 'wet' : 'stand')
    : (!washStarted && coverage < 8) ? 'stand'
    : coverage < 38 ? 's1'
    : coverage < 70 ? 's2'
    : 's3'

  // On each stage change, fire the matching poof and swap the visible pose at
  // the poof's peak so the sticker change is hidden inside the burst.
  useEffect(() => {
    const prev = prevStageRef.current
    if (targetStage === prev) return
    prevStageRef.current = targetStage
    const type = poofTypeFor(prev, targetStage)
    setPoof({ type, key: ++poofKeyRef.current })
    // He shakes the spray off on every rinse transition. During the finish the
    // s1→wet swap already shakes via erenShakeDry, but the CLOSING wet→stand
    // explosion (targetStage 'stand' while done) only hopped — shake there too
    // so the very last splash reads as him shaking the water off.
    if (type === 'water' && (!doneRef.current || targetStage === 'stand')) {
      washShakeRef.current?.animate(WASH_SHAKE_KEYFRAMES, WASH_SHAKE_TIMING)
    }
    const t = setTimeout(() => setVisibleStage(targetStage), WASH_POOF_PEAK_MS)
    return () => clearTimeout(t)
  }, [targetStage])

  // Memoize the bare sprite so per-pointermove coverage/bubble renders don't
  // reconcile it (same pattern as FeedScene). Cleanliness is the only live
  // input — it drives StinkyFlies.
  const washEren = useRoomEren('wash', WASH_EREN_FALLBACK)
  const erenSprite = useMemo(() => (
    <>
      {/* Bathroom idle pose (ErenBathroomHat) or a Closet skin. */}
      <BlinkingEren size={200} {...washEren} />
      <StinkyFlies cleanliness={cleanliness} />
    </>
  ), [cleanliness, washEren])

  // Apply initial positions to DOM
  useEffect(() => {
    if (soapRef.current) {
      soapRef.current.style.left = `${soapPosRef.current.x}%`
      soapRef.current.style.top  = `${soapPosRef.current.y}%`
    }
    if (showerRef.current) {
      showerRef.current.style.left = `${showerPosRef.current.x}%`
      showerRef.current.style.top  = `${showerPosRef.current.y}%`
    }
  }, [])

  // Stop touch events from bubbling to CareSceneHost swipe handler
  function stopTouchBubble(e: React.TouchEvent) { e.stopPropagation() }

  // ── Soap pointer handlers ─────────────────────────────────────────────────
  function onSoapDown(e: React.PointerEvent) {
    if (doneRef.current || isSleeping) return
    e.currentTarget.setPointerCapture(e.pointerId)
    dragSoapRef.current = true
    setDragSoap(true)
  }

  // True only when the pointer is over Eren's actual silhouette. Reads his
  // live on-screen box (so it tracks his centered, bottom-anchored position at
  // any viewport size) and tests it against the sprite's occupancy mask — soap
  // and water only register on him, never the floor or walls.
  const isOverEren = useCallback((clientX: number, clientY: number) => {
    const r = erenRef.current?.getBoundingClientRect()
    if (!r || r.width === 0) return false
    const col = Math.floor(((clientX - r.left) / r.width)  * MASK_COLS)
    const row = Math.floor(((clientY - r.top)  / r.height) * MASK_ROWS)
    if (col < 0 || row < 0 || col >= MASK_COLS || row >= MASK_ROWS) return false
    return EREN_MASK[row][col] === '1'
  }, [])

  const onPointerMove = useCallback((e: React.PointerEvent) => {
    const rect = sceneRef.current?.getBoundingClientRect()
    if (!rect) return
    const px = ((e.clientX - rect.left) / rect.width)  * 100
    const py = ((e.clientY - rect.top)  / rect.height) * 100

    if (dragSoapRef.current && !doneRef.current) {
      // Move soap directly via DOM — no re-render
      soapPosRef.current = { x: px, y: py }
      if (soapRef.current) {
        soapRef.current.style.left = `${px}%`
        soapRef.current.style.top  = `${py}%`
      }
      if (isOverEren(e.clientX, e.clientY)) {
        markScrub()
        const now = Date.now()
        if (now - lastScrubWordRef.current > 1200) {
          lastScrubWordRef.current = now
          setScrubWordKey(k => k + 1)
        }
        setCoverage(c => {
          // +0.5 per in-zone soap stroke: soaping up to the 95% shower-unlock
          // stays quick (it dragged at 0.22) while the lather still climbs
          // through s1→s2→s3 so the pose progression reads.
          const next = Math.min(100, c + 0.5)
          coverageRef.current = next
          if (next >= 95 && !showShowerRef.current) {
            showShowerRef.current = true
            setShowShower(true)
          }
          return next
        })
        setBubbles(bs => {
          // Stamp the bubble with the coverage AT creation so the rinse
          // can fade it out individually based on how far past its
          // creation moment we've drained the soap.
          const next = [...bs, { id: bubbleId.current++, x: px, y: py, size: 14 + Math.random() * 12, c: coverageRef.current }]
          return next.slice(-40)
        })
      }
    }

    if (dragShowerRef.current && !doneRef.current) {
      // Move shower directly via DOM — no re-render
      showerPosRef.current = { x: px, y: py }
      if (showerRef.current) {
        showerRef.current.style.left = `${px}%`
        showerRef.current.style.top  = `${py}%`
      }
      // Rinse keeps the original generous zone — the shower just drains
      // coverage (no suds are painted off-body), and rinsing is a slow drag,
      // so a forgiving target keeps it from feeling tedious.
      if (px > 22 && px < 78 && py > 55 && py < 95) {
        // Only drain coverage — bubbles fade out automatically in the
        // render layer based on each bubble's creation coverage vs the
        // current coverage. We don't pop them from the array, which is
        // what made them disappear instantly before.
        setCoverage(c => {
          const next = Math.max(0, c - 0.6)
          coverageRef.current = next
          return next
        })
      }
    }
  }, [])

  function onSoapUp() {
    dragSoapRef.current = false
    setDragSoap(false)
  }

  function onShowerDown(e: React.PointerEvent) {
    if (doneRef.current || isSleeping || coverageRef.current < 80) return
    e.currentTarget.setPointerCapture(e.pointerId)
    dragShowerRef.current = true
    setDragShower(true)
  }

  function onShowerUp() {
    dragShowerRef.current = false
    setDragShower(false)
    if (coverageRef.current <= 10 && !doneRef.current) finishWash()
  }

  async function finishWash() {
    if (!user?.id || doneRef.current) return
    doneRef.current = true
    setDone(true)
    setScrubbing(false)
    // Wet-dog shake → droplets fly off → clean sparkle → happy finisher.
    reaction.play([
      { name: 'shake',   ms: 750, onEnter: () => playSound('care_splash') },
      { name: 'sparkle', ms: 1150 },
      ...happyFinisherBeats(),
    ])
    setSaving(true)
    try {
      const result = await applyAction(user.id, 'wash')
      setToast(result.message)
      if (result.success) completeTask('daily_wash')
    } catch {
      setToast('Something went wrong')
    } finally {
      setSaving(false)
      setTimeout(() => setToast(null), 3000)
    }
  }

  return (
    <div
      ref={sceneRef}
      className="fixed inset-0 z-40 overflow-hidden select-none"
      style={{ touchAction: 'none' }}
    >
      {wish?.wish && (
        <WishHintBanner text={wish.text} status={wish.status} matchesThisRoom={wishMatchesThisRoom} />
      )}
      {/* ══ BACKGROUND IMAGE ══ */}
      <div className="absolute inset-0" style={{ backgroundImage: `url(${isDark ? '/BathroomDark.png' : '/bathroom.png'})`, backgroundSize: 'cover', backgroundPosition: 'center', WebkitTouchCallout: 'none', WebkitUserSelect: 'none', userSelect: 'none', pointerEvents: 'none' }} />

      {/* ══ CANDLE FLAME (night only) ═════════════════════════════════════
        Overlays the painted flame of the candle on the stool right of the
        bathtub. The background uses `cover + center`, so fixed screen-percent
        coords drift with the viewport's aspect ratio — this wrapper recreates
        the exact cover mapping (768×1376 source), letting the flame be placed
        in image coordinates. Pixel-scanned: flame core spans (676–690,
        823–845), center x 683, in BathroomDark.png. */}
      {isDark && (
        <div className="absolute pointer-events-none" style={{
          left: '50%', top: '50%',
          transform: 'translate(-50%, -50%)',
          width: 'max(100vw, calc(100dvh * 768 / 1376))',
          aspectRatio: '768 / 1376',
          zIndex: 12,
        }}>
          {/* Outer warm halo on the wall behind the candle */}
          <div style={{
            position: 'absolute',
            left: '88.93%', top: '60.57%',
            width: 36, height: 36,
            transform: 'translate(-50%, -50%)',
            background: 'radial-gradient(circle, rgba(255,180,80,0.35) 0%, rgba(255,160,60,0.12) 50%, transparent 80%)',
            mixBlendMode: 'screen',
          }} />
          {/* The flame itself — sized in image % so it hugs the painted flame
              at every screen size. The candleFlame keyframes carry the
              translateX(-50%) that centers it on `left`. */}
          <div style={{
            position: 'absolute',
            left: '88.93%', top: '59.81%',
            width: '1.82%', height: '1.6%',
            background: 'radial-gradient(ellipse at 50% 75%, #FFF2B0 0%, #FFCC55 30%, #FF8020 65%, #B83820 90%, transparent 100%)',
            borderRadius: '50% 50% 35% 35% / 60% 60% 40% 40%',
            boxShadow: '0 0 6px rgba(255,180,60,0.8), 0 0 14px rgba(255,140,40,0.45)',
            transformOrigin: '50% 100%',
            animation: 'candleFlame 1.6s ease-in-out infinite',
          }} />
        </div>
      )}

      {/* ══ TAP DRIP ══════════════════════════════════════════════════════
        At night the tap sits lower in BathroomDark.png, so spawn point
        drops; vanish point pulls *up* though, since the night sink is
        shallower. --tap-drop-distance overrides the keyframe end value. */}
      <div className="absolute pointer-events-none" style={{
        left: 'calc(50% + 2px)',
        top: `calc(50% + ${isDark ? 24 : 14}px)`,
        zIndex: 15,
        ...(isDark ? { ['--tap-drop-distance' as string]: 'calc(4vh + 4px)' } : {}),
      } as React.CSSProperties}>
        <div className="tap-drop" />
      </div>

      {/* ══ PIXEL EREN ════════════════════════════════════════════════════ */}
      {/* Hidden while sleeping in the bedroom. Body wrapper: squirm while
          being soaped, shake-dry then a happy hop on finish. Idle pauses
          during the finish reaction. */}
      {!isSleeping && (
        <div ref={erenRef} className={cn('absolute transition-all duration-500', done ? 'bottom-[12%]' : 'bottom-[10%]')}
          style={{ left: '50%', transform: 'translateX(-50%)' }}>
          <ErenIdleLayer disabled={scrubbing || reaction.active}>
            <div style={{
              position: 'relative', width: 200, height: 200,
              animation: reaction.phase === 'shake' ? 'erenShakeDry 750ms linear'
                : reaction.phase === 'finish' ? 'erenIdleHop 800ms ease-in-out'
                : scrubbing ? 'erenSquirm 400ms steps(2) infinite'
                : undefined,
              transformOrigin: 'bottom center',
            }}>
              {/* Shake wrapper — a rinse transition fires WASH_SHAKE_KEYFRAMES on
                  this via WAAPI so he shakes the water off; pivots at the feet. */}
              <div ref={washShakeRef} style={{ position: 'relative', width: '100%', height: '100%', transformOrigin: 'bottom center' }}>
                {/* Standing sprite when dry; lather/wet pose sticker otherwise.
                    The 200×200 box stays fixed (erenRef) so the soap occupancy
                    mask keeps lining up regardless of which pose shows. The pose
                    is lifted 20px because the standing sprite's feet sit ~20px
                    above the box bottom (its source has bottom padding) — without
                    this the pose lands lower and he looks like he drops on swap. */}
                {visibleStage === 'stand' ? erenSprite : (
                  <div style={{ position: 'absolute', left: '50%', bottom: 20, transform: 'translateX(-50%)' }}>
                    {/* width 108 ≈ the standing cat's on-screen silhouette
                        (~107×155 → pose aspect ~0.67 gives ~108×159), so head
                        and body match and he doesn't visibly shrink on the first
                        soap swap. Earlier 125–190 values were dead: the `left:50%`
                        wrapper + Tailwind's `img{max-width:100%}` capped every
                        pose to ~100px until PoseSprite opted out of that cap. */}
                    <PoseSprite src={WASH_POSE_SRC[visibleStage]} width={108} />
                  </div>
                )}
              </div>
            </div>
          </ErenIdleLayer>

          {/* Bubble (soaping) / splash (rinsing) poof masks each pose swap. */}
          {poof && (poof.type === 'bubble'
            ? <BubblePoof key={poof.key} size={210} onDone={() => setPoof(null)} />
            : <SplashPoof key={poof.key} size={240} onDone={() => setPoof(null)} />)}

          {/* Reaction particles + words, anchored to Eren's 200px box. */}
          {scrubbing && scrubWordKey > 0 &&
            <SoundWord key={scrubWordKey} word="SCRUB SCRUB" color={WORD_COLOR.water} left={50} top={2} size={6} />}
          {reaction.phase === 'shake' && <>
            <Droplets bottom="40%" />
            <SoundWord word="SPLASH!" color={WORD_COLOR.water} left={50} top={4} />
          </>}
          {reaction.phase === 'sparkle' && <Sparkles />}
          {reaction.phase === 'finish' && <>
            <Hearts count={2} bottom="58%" />
            <SoundWord word="CLEAN!" color={WORD_COLOR.happy} left={50} top={6} />
          </>}
        </div>
      )}

      {/* ══ SOAP SUDS ═════════════════════════════════════════════════════
        Each bubble fades from 1 → 0 as the current coverage drops
        between its creation coverage and a small anchor near the
        finish threshold. Effect: bubbles wash off individually,
        newest-on-top first, and all are gone before the rinse
        completes (`coverage` ≤ 5). */}
      <div className="absolute inset-0 pointer-events-none z-20">
        {bubbles.map(b => {
          const FADE_ANCHOR = 5
          const range = Math.max(15, b.c - FADE_ANCHOR)
          // Barely-there: the lather/soap now lives in the pose art itself, so
          // the painted suds are just a faint "where you scrubbed" hint.
          const op = Math.max(0, Math.min(1, (coverage - FADE_ANCHOR) / range)) * 0.2
          if (op <= 0.01) return null
          return (
            <div key={b.id} className="absolute rounded-full"
              style={{
                left: `${b.x}%`, top: `${b.y}%`, width: b.size, height: b.size,
                transform: 'translate(-50%,-50%)',
                background: 'radial-gradient(circle at 35% 35%, rgba(255,255,255,0.95), rgba(200,230,255,0.6))',
                border: '1px solid rgba(150,200,255,0.5)',
                boxShadow: 'inset 1px 1px 2px rgba(255,255,255,0.8)',
                opacity: op,
                transition: 'opacity 0.25s linear',
              }} />
          )
        })}
      </div>

      {/* ══ SHOWER HEAD ═══════════════════════════════════════════════════ */}
      <div
        ref={showerRef}
        className={cn('absolute z-30', (isSleeping || !showShower) ? 'opacity-0 pointer-events-none' : 'opacity-100', dragShower ? 'cursor-grabbing' : 'cursor-grab')}
        style={{ left: '75%', top: '30%', transform: 'translate(-50%, -50%)', touchAction: 'none' }}
        onPointerDown={onShowerDown}
        onPointerMove={onPointerMove}
        onPointerUp={onShowerUp}
        onTouchStart={stopTouchBubble}
        onTouchMove={stopTouchBubble}
        onTouchEnd={stopTouchBubble}
      >
        {/* Sprite + spray share one positioned box so the water stays pinned
            to the perforated plate (≈DISC_X/DISC_Y of the sprite) at any size. */}
        <div className="relative" style={{ width: SHOWER_W, height: SHOWER_H }}>
          <img src="/shower.png?v=1" alt="" draggable={false}
            style={{ width: '100%', height: '100%', display: 'block', pointerEvents: 'none', filter: 'drop-shadow(1px 2px 1px rgba(40,70,110,0.35))' }} />
          {/* Water — emanates from the plate and fans down-left, the way the
              plate's face points. Only while the head is held (dragShower). */}
          {dragShower && (
            <div className="absolute pointer-events-none" style={{ left: `${DISC_X}%`, top: `${DISC_Y}%`, width: 0, height: 0, zIndex: 1 }}>
              <div className="shower-mist" />
              {SPRAY_RAYS.map((deg, i) => (
                <div key={i} className="spray-ray" style={{ transform: `rotate(${deg}deg)` }}>
                  {[0, 1, 2].map(j => (
                    <span key={j} className="spray-drop" style={{
                      animationDelay: `${(i * 0.05 + j * 0.16).toFixed(2)}s`,
                      ['--len' as string]: `${42 + ((i + j) % 3) * 10}px`,
                    } as React.CSSProperties} />
                  ))}
                </div>
              ))}
            </div>
          )}
        </div>
        {showShower && (
          <div className="absolute -bottom-5 left-1/2 -translate-x-1/2 whitespace-nowrap font-pixel text-sky-600" style={{ fontSize: 6 }}>
            {coverage <= 15 ? 'DONE SOON!' : 'DRAG TO RINSE!'}
          </div>
        )}
      </div>

      {/* ══ SOAP BAR ══════════════════════════════════════════════════════ */}
      <div
        ref={soapRef}
        className={cn('absolute z-30', dragSoap ? 'cursor-grabbing scale-110' : 'cursor-grab', (done || isSleeping) && 'opacity-0 pointer-events-none')}
        style={{ left: '12%', top: '62%', transform: 'translate(-50%,-50%)', touchAction: 'none' }}
        onPointerDown={onSoapDown}
        onPointerMove={onPointerMove}
        onPointerUp={onSoapUp}
        onTouchStart={stopTouchBubble}
        onTouchMove={stopTouchBubble}
        onTouchEnd={stopTouchBubble}
      >
        <img src="/soap.png?v=1" alt="" draggable={false}
          style={{ width: SOAP_W, height: SOAP_H, display: 'block', pointerEvents: 'none', filter: 'drop-shadow(2px 3px 0 rgba(153,26,90,0.32))' }} />
        {!dragSoap && !showShower && (
          <div className="absolute -bottom-5 left-1/2 -translate-x-1/2 whitespace-nowrap font-pixel text-pink-500" style={{ fontSize: 6 }}>
            DRAG ON EREN!
          </div>
        )}
      </div>

      {/* ══ SCENE LABEL ══════════════════════════════════════════════════ */}
      <div className="absolute left-1/2 -translate-x-1/2 z-50" style={{ top: 110 }}>
        <span className="font-pixel text-sky-700 px-3 py-1.5"
          style={{ background: 'linear-gradient(135deg, #E8F8FF, #D0EEFF)', borderRadius: 3, border: '2px solid #A8D4F0', boxShadow: '2px 2px 0 #88B8D8', fontSize: 7 }}>
          BATHROOM
        </span>
      </div>

      {/* ══ TOAST ════════════════════════════════════════════════════════ */}
      {toast && (
        <div className="absolute top-14 left-1/2 -translate-x-1/2 z-50 text-white px-4 py-2.5 animate-float whitespace-nowrap"
          style={{ background: '#1F3A4E', borderRadius: 3, border: '2px solid #3A6A8E', boxShadow: '3px 3px 0 rgba(0,0,0,0.4)', fontFamily: '"Press Start 2P"', fontSize: 7 }}>
          {toast}
        </div>
      )}

      {/* ══ PROGRESS BARS ════════════════════════════════════════════════ */}
      <div className="absolute bottom-4 inset-x-0 px-5 flex flex-col gap-2 items-center pointer-events-none">
        {!done && (
          <div className="w-full max-w-xs pointer-events-none flex flex-col gap-2.5"
            style={{ background: '#1A2A38', borderRadius: 6, border: '2px solid #3A5A70', boxShadow: '3px 3px 0 rgba(0,0,0,0.4)', padding: '11px 12px' }}>
            <SegmentMeter
              label="SOAP"
              value={coverage}
              valueText={`${Math.round(coverage)}%`}
              palette={SOAP_METER}
              labelColor="#9BDCF7"
              valueColor="#CFEFFF"
            />
            {showShower && (
              <SegmentMeter
                label="RINSE"
                value={Math.max(0, 100 - coverage)}
                valueText={`${Math.round(Math.max(0, 100 - coverage))}%`}
                palette={RINSE_METER}
                labelColor="#9BDCF7"
                valueColor="#CFEFFF"
              />
            )}
            {showShower && !saving && coverage > 10 && (
              <p className="font-pixel text-sky-400 text-center" style={{ fontSize: 6 }}>DRAG SHOWER TO RINSE!</p>
            )}
            {saving && <p className="font-pixel text-sky-400 text-center animate-pulse" style={{ fontSize: 6 }}>SAVING...</p>}
          </div>
        )}
        {done && <SqueakyCleanBanner />}
      </div>

      <style jsx>{`
        /* ── Shower spray ──
           A fan of rotated rays pinned to the perforated plate. Each ray is a
           zero-size pivot; its drops translate straight down in their own
           frame and the ray's rotation tips that travel down-LEFT, so the
           water leaves the plate the way its face points. translate+opacity
           only = stays on the compositor. */
        .spray-ray  { position: absolute; left: 0; top: 0; transform-origin: top center; }
        .spray-drop {
          position: absolute; top: 0; left: -1px;
          width: 2px; height: 9px;
          border-radius: 60% 60% 70% 70% / 30% 30% 80% 80%;
          background: linear-gradient(180deg, rgba(216,241,252,0.95) 0%, rgba(96,182,232,0.96) 100%);
          box-shadow: 0 0 3px rgba(120,200,240,0.55);
          opacity: 0;
          animation: sprayFall 0.5s linear infinite;
        }
        @keyframes sprayFall {
          0%   { transform: translateY(0)               scaleY(0.6);  opacity: 0; }
          16%  { opacity: 0.95; }
          82%  { opacity: 0.85; }
          100% { transform: translateY(var(--len, 60px)) scaleY(1.3); opacity: 0; }
        }
        .shower-mist {
          position: absolute; left: -6px; top: -4px;
          width: 18px; height: 14px; border-radius: 50%;
          background: radial-gradient(circle at 60% 35%, rgba(222,243,253,0.5) 0%, rgba(150,210,240,0.18) 55%, transparent 75%);
          animation: showerMist 0.6s ease-in-out infinite;
        }
        @keyframes showerMist {
          0%, 100% { opacity: 0.45; transform: scale(1); }
          50%      { opacity: 0.8;  transform: scale(1.14); }
        }

        .tap-drop {
          position: absolute;
          left: 0;
          top: 0;
          margin-left: -2px;
          width: 4px;
          height: 6px;
          background: linear-gradient(180deg, rgba(200,230,245,0.85) 0%, rgba(110,180,225,0.98) 100%);
          border-radius: 50% 50% 55% 55% / 35% 35% 85% 85%;
          box-shadow:
            0 0 3px rgba(110,180,230,0.7),
            inset 1px 1px 0 rgba(255,255,255,0.7),
            inset -1px -1px 0 rgba(70,140,190,0.25);
          animation: tapDrop 1.6s cubic-bezier(0.45, 0, 0.85, 0.4) infinite;
          transform-origin: top center;
          opacity: 0;
        }
        @keyframes tapDrop {
          0%   { transform: translateY(-3px) scale(0.6, 0.4); opacity: 0; }
          5%   { transform: translateY(0) scale(1, 1); opacity: 1; }
          24%  { transform: translateY(var(--tap-drop-distance, calc(4vh + 7px))) scale(0.85, 1.3); opacity: 1; }
          25%, 100% { transform: translateY(var(--tap-drop-distance, calc(4vh + 7px))) scale(1, 1); opacity: 0; }
        }
      `}</style>

      <LightSwitch targetBottom="12%" targetLeft="50%" persistKey="bathroom" />
    </div>
  )
}
