'use client'

import { useState, useRef, useCallback, useEffect, useMemo } from 'react'
import { useAuth } from '@/hooks/useAuth'
import { useErenStats, getCachedIsSleeping } from '@/hooks/useErenStats'
import { useTasks } from '@/contexts/TaskContext'
import { cn } from '@/lib/utils'
import BlinkingEren from '@/components/BlinkingEren'
import ErenIdleLayer from '@/components/ErenIdleLayer'
import StinkyFlies from '@/components/StinkyFlies'
import LightSwitch from '@/components/LightSwitch'
import { useIsDark } from '@/hooks/useIsDark'
import { useWish } from '@/contexts/WishContext'
import WishHintBanner from '@/components/wish/WishHintBanner'
import { wishHintRoom } from '@/lib/wishes'
import { playSound } from '@/lib/sounds'
import { useErenReaction } from '@/hooks/useErenReaction'
import { happyFinisherBeats, WORD_COLOR } from '@/lib/erenReactions'
import SoundWord from '@/components/SoundWord'
import { Droplets, Sparkles, Hearts } from '@/components/care/ReactionFx'

interface Props { onClose: () => void }
// `c` = coverage % at the time this bubble was created. Used to fade
// each bubble out individually as the rinse progresses past its
// creation moment (newest/topmost bubbles wash off first).
interface Bubble { id: number; x: number; y: number; size: number; c: number }

// Eren's silhouette in the bathroom (ErenBathroomHat pose) as a 24×24
// occupancy grid over his 200px sprite box: '1' = a cell his body/hat/tail
// covers. Generated by scripts/measure_bath_mask.js from the sprite's alpha,
// then the two interior gaps (between the ear tips, row 3, and between the
// front paws, row 21) were filled by hand so a continuous scrub across his
// head or feet doesn't stutter. Used to confine soap suds to his body so
// nothing lands on the floor, walls, or the empty corners of his box.
const EREN_MASK = [
  '000000000000000000000000',
  '000000000000000000000000',
  '000000000000000000000000',
  '000000111111111000000000',
  '000001111111111100000000',
  '000001111111111100000000',
  '000001111111111100000000',
  '000000111111111000000000',
  '000001111111111100000000',
  '000001111111111100000000',
  '000001111111111100000000',
  '000001111111111110000000',
  '000000111111111111000000',
  '000000111111111111000000',
  '000000111111111111000000',
  '000001111111111111000000',
  '000001111111111111000000',
  '000001111111111111000000',
  '000000111111111110000000',
  '000000111111111100000000',
  '000000011111111000000000',
  '000000001111100000000000',
  '000000000000000000000000',
  '000000000000000000000000',
]
const MASK_COLS = 24
const MASK_ROWS = 24

export default function WashScene({ onClose }: Props) {
  const { user, profile } = useAuth()
  const { stats, applyAction } = useErenStats(profile?.household_id ?? null)
  const { completeTask } = useTasks()
  const wish = useWish()
  const wishMatchesThisRoom = wish?.wish ? wishHintRoom(wish.wish) === 'wash' : false

  const sceneRef   = useRef<HTMLDivElement>(null)
  const soapRef    = useRef<HTMLDivElement>(null)
  const showerRef  = useRef<HTMLDivElement>(null)
  const erenRef    = useRef<HTMLDivElement>(null)

  // Positions stored in refs — updated directly on DOM, no re-render
  const soapPosRef   = useRef({ x: 12, y: 62 })
  const showerPosRef = useRef({ x: 75, y: 30 })

  const [dragSoap,   setDragSoap]   = useState(false)
  const [dragShower, setDragShower] = useState(false)
  const [coverage,   setCoverage]   = useState(0)
  const [bubbles,    setBubbles]    = useState<Bubble[]>([])
  const [showShower, setShowShower] = useState(false)
  const [done,       setDone]       = useState(false)
  const [saving,     setSaving]     = useState(false)
  const [toast,      setToast]      = useState<string | null>(null)

  const bubbleId      = useRef(0)
  const dragSoapRef   = useRef(false)
  const dragShowerRef = useRef(false)
  const doneRef       = useRef(false)
  const showShowerRef = useRef(false)
  const coverageRef   = useRef(0)

  const cleanliness = stats?.cleanliness ?? 100
  const isDark = useIsDark()
  // Cache fallback so Eren renders synchronously with the right state.
  const isSleeping = stats?.is_sleeping ?? getCachedIsSleeping() ?? true

  // Reaction runner — squirm while being soaped, shake-dry + sparkle on finish.
  const reaction = useErenReaction()
  const [scrubbing, setScrubbing] = useState(false)
  const scrubStopRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  // Mark "being scrubbed" on each in-zone soap move; auto-clear ~250ms after
  // the last one so a continuous scrub holds the squirm but pausing stops it.
  const markScrub = useCallback(() => {
    setScrubbing(true)
    if (scrubStopRef.current) clearTimeout(scrubStopRef.current)
    scrubStopRef.current = setTimeout(() => setScrubbing(false), 250)
  }, [])
  useEffect(() => () => { if (scrubStopRef.current) clearTimeout(scrubStopRef.current) }, [])
  // Throttle the "SCRUB SCRUB" word so it pops at most ~once/1.2s while soaping.
  const lastScrubWordRef = useRef(0)
  const [scrubWordKey, setScrubWordKey] = useState(0)
  // Throttle the looping soap-rub / shower-hiss SFX so dragging him strings
  // together a continuous water sound without spamming a play per pointermove.
  const lastSoapSndRef  = useRef(0)
  const lastRinseSndRef = useRef(0)

  // Memoize the bare sprite so per-pointermove coverage/bubble renders don't
  // reconcile it (same pattern as FeedScene). Cleanliness is the only live
  // input — it drives StinkyFlies.
  const erenSprite = useMemo(() => (
    <>
      {/* Bathroom pose: ErenBathroomHat.png — blue beanie sits low on
          the forehead so the face/eyes drop ~4% from the default, and
          the eyes sit further LEFT than the everyday sprite. Coords are
          measured to this sprite's eye centers (≈37.3% / 51.3% across)
          so the blink + glint land dead-center on each eye. */}
      {/* Coords from a precise pixel-scan of ErenBathroomHat.png.
          Image is 871×1537 and the cat is NOT centered in its
          canvas — there's extra transparent space on the right
          — so image-relative % values translate awkwardly. The
          numbers below are container-relative (200×200 box,
          portrait sprite height-fits so the image occupies the
          middle ~56.6% of container width, starting at x≈21.7%).
          Catchlights are MIRRORED, not same-position: A in the
          upper-RIGHT of its iris, B in the upper-LEFT. */}
      <BlinkingEren size={200} src="/ErenBathroomHat_notail.png" tailSrc="/ErenBathroomHat_tail.png" tailOrigin="65.9% 77.6%" eyes={{
        lidTop:    '36.34%',
        lidWidth:  '5.4%',
        lidLeftA:  '34.38%',
        lidLeftB:  '48.21%',
        maskTop:   '36.34%',
        maskLeftA: '34.38%',
        maskLeftB: '48.21%',
        maskW:     '5.4%',
        maskH:     '4.36%',
        // Catchlight in eye A sits at ~70% across × ~13% down of
        // its iris. Glint top-left = center - radius.
        glintLeftA: '59%',
        glintTopA:  '2%',
        // Catchlight in eye B sits at ~31% across × ~13% down.
        glintLeftB: '20%',
        glintTopB:  '2%',
        glintW:     '22%',
      }} />
      <StinkyFlies cleanliness={cleanliness} />
    </>
  ), [cleanliness])

  // Apply initial positions to DOM
  useEffect(() => {
    if (soapRef.current) {
      soapRef.current.style.left = `${soapPosRef.current.x}%`
      soapRef.current.style.top  = `${soapPosRef.current.y}%`
    }
    if (showerRef.current) {
      showerRef.current.style.left = `${showerPosRef.current.x}%`
      showerRef.current.style.top  = `${showerPosRef.current.y}%`
    }
  }, [])

  // Stop touch events from bubbling to CareSceneHost swipe handler
  function stopTouchBubble(e: React.TouchEvent) { e.stopPropagation() }

  // ── Soap pointer handlers ─────────────────────────────────────────────────
  function onSoapDown(e: React.PointerEvent) {
    if (doneRef.current || isSleeping) return
    e.currentTarget.setPointerCapture(e.pointerId)
    dragSoapRef.current = true
    setDragSoap(true)
  }

  // True only when the pointer is over Eren's actual silhouette. Reads his
  // live on-screen box (so it tracks his centered, bottom-anchored position at
  // any viewport size) and tests it against the sprite's occupancy mask — soap
  // and water only register on him, never the floor or walls.
  const isOverEren = useCallback((clientX: number, clientY: number) => {
    const r = erenRef.current?.getBoundingClientRect()
    if (!r || r.width === 0) return false
    const col = Math.floor(((clientX - r.left) / r.width)  * MASK_COLS)
    const row = Math.floor(((clientY - r.top)  / r.height) * MASK_ROWS)
    if (col < 0 || row < 0 || col >= MASK_COLS || row >= MASK_ROWS) return false
    return EREN_MASK[row][col] === '1'
  }, [])

  const onPointerMove = useCallback((e: React.PointerEvent) => {
    const rect = sceneRef.current?.getBoundingClientRect()
    if (!rect) return
    const px = ((e.clientX - rect.left) / rect.width)  * 100
    const py = ((e.clientY - rect.top)  / rect.height) * 100

    if (dragSoapRef.current && !doneRef.current) {
      // Move soap directly via DOM — no re-render
      soapPosRef.current = { x: px, y: py }
      if (soapRef.current) {
        soapRef.current.style.left = `${px}%`
        soapRef.current.style.top  = `${py}%`
      }
      if (isOverEren(e.clientX, e.clientY)) {
        markScrub()
        const now = Date.now()
        // Soft soap-rub sound, strung together every ~260ms while soaping.
        if (now - lastSoapSndRef.current > 260) {
          lastSoapSndRef.current = now
          playSound('care_soap')
        }
        if (now - lastScrubWordRef.current > 1200) {
          lastScrubWordRef.current = now
          setScrubWordKey(k => k + 1)
        }
        setCoverage(c => {
          // +0.4 per in-zone soap stroke (was 0.7): soaping him up to the 95%
          // shower-unlock takes noticeably longer, so the scrub feels earned.
          const next = Math.min(100, c + 0.4)
          coverageRef.current = next
          if (next >= 95 && !showShowerRef.current) {
            showShowerRef.current = true
            setShowShower(true)
          }
          return next
        })
        setBubbles(bs => {
          // Stamp the bubble with the coverage AT creation so the rinse
          // can fade it out individually based on how far past its
          // creation moment we've drained the soap.
          const next = [...bs, { id: bubbleId.current++, x: px, y: py, size: 14 + Math.random() * 12, c: coverageRef.current }]
          return next.slice(-40)
        })
      }
    }

    if (dragShowerRef.current && !doneRef.current) {
      // Move shower directly via DOM — no re-render
      showerPosRef.current = { x: px, y: py }
      if (showerRef.current) {
        showerRef.current.style.left = `${px}%`
        showerRef.current.style.top  = `${py}%`
      }
      // Rinse keeps the original generous zone — the shower just drains
      // coverage (no suds are painted off-body), and rinsing is a slow drag,
      // so a forgiving target keeps it from feeling tedious.
      if (px > 22 && px < 78 && py > 55 && py < 95) {
        // Running shower-water hiss while rinsing him off (~240ms cadence).
        const now = Date.now()
        if (now - lastRinseSndRef.current > 240) {
          lastRinseSndRef.current = now
          playSound('care_rinse')
        }
        // Only drain coverage — bubbles fade out automatically in the
        // render layer based on each bubble's creation coverage vs the
        // current coverage. We don't pop them from the array, which is
        // what made them disappear instantly before.
        setCoverage(c => {
          const next = Math.max(0, c - 0.3)
          coverageRef.current = next
          return next
        })
      }
    }
  }, [])

  function onSoapUp() {
    dragSoapRef.current = false
    setDragSoap(false)
  }

  function onShowerDown(e: React.PointerEvent) {
    if (doneRef.current || isSleeping || coverageRef.current < 80) return
    e.currentTarget.setPointerCapture(e.pointerId)
    dragShowerRef.current = true
    setDragShower(true)
  }

  function onShowerUp() {
    dragShowerRef.current = false
    setDragShower(false)
    if (coverageRef.current <= 10 && !doneRef.current) finishWash()
  }

  async function finishWash() {
    if (!user?.id || doneRef.current) return
    doneRef.current = true
    setDone(true)
    setScrubbing(false)
    // Wet-dog shake → droplets fly off → clean sparkle → happy finisher.
    reaction.play([
      { name: 'shake',   ms: 750, onEnter: () => playSound('care_splash') },
      { name: 'sparkle', ms: 1150 },
      ...happyFinisherBeats(),
    ])
    setSaving(true)
    try {
      const result = await applyAction(user.id, 'wash')
      setToast(result.message)
      if (result.success) completeTask('daily_wash')
    } catch {
      setToast('Something went wrong')
    } finally {
      setSaving(false)
      setTimeout(() => setToast(null), 3000)
    }
  }

  const SOAP_SEGMENTS = 12
  const soapFilled  = Math.round((coverage / 100) * SOAP_SEGMENTS)
  const rinseFilled = showShower ? Math.round(Math.max(0, (100 - coverage) / 100) * SOAP_SEGMENTS) : 0

  return (
    <div
      ref={sceneRef}
      className="fixed inset-0 z-40 overflow-hidden select-none"
      style={{ touchAction: 'none' }}
    >
      {wish?.wish && (
        <WishHintBanner text={wish.text} status={wish.status} matchesThisRoom={wishMatchesThisRoom} />
      )}
      {/* ══ BACKGROUND IMAGE ══ */}
      <div className="absolute inset-0" style={{ backgroundImage: `url(${isDark ? '/BathroomDark.png' : '/bathroom.png'})`, backgroundSize: 'cover', backgroundPosition: 'center', WebkitTouchCallout: 'none', WebkitUserSelect: 'none', userSelect: 'none', pointerEvents: 'none' }} />

      {/* ══ CANDLE FLAME (night only) ═════════════════════════════════════
        Overlays the painted flame of the candle on the stool right of the
        bathtub. The background uses `cover + center`, so fixed screen-percent
        coords drift with the viewport's aspect ratio — this wrapper recreates
        the exact cover mapping (768×1376 source), letting the flame be placed
        in image coordinates. Pixel-scanned: flame core spans (676–690,
        823–845), center x 683, in BathroomDark.png. */}
      {isDark && (
        <div className="absolute pointer-events-none" style={{
          left: '50%', top: '50%',
          transform: 'translate(-50%, -50%)',
          width: 'max(100vw, calc(100dvh * 768 / 1376))',
          aspectRatio: '768 / 1376',
          zIndex: 12,
        }}>
          {/* Outer warm halo on the wall behind the candle */}
          <div style={{
            position: 'absolute',
            left: '88.93%', top: '60.57%',
            width: 36, height: 36,
            transform: 'translate(-50%, -50%)',
            background: 'radial-gradient(circle, rgba(255,180,80,0.35) 0%, rgba(255,160,60,0.12) 50%, transparent 80%)',
            mixBlendMode: 'screen',
          }} />
          {/* The flame itself — sized in image % so it hugs the painted flame
              at every screen size. The candleFlame keyframes carry the
              translateX(-50%) that centers it on `left`. */}
          <div style={{
            position: 'absolute',
            left: '88.93%', top: '59.81%',
            width: '1.82%', height: '1.6%',
            background: 'radial-gradient(ellipse at 50% 75%, #FFF2B0 0%, #FFCC55 30%, #FF8020 65%, #B83820 90%, transparent 100%)',
            borderRadius: '50% 50% 35% 35% / 60% 60% 40% 40%',
            boxShadow: '0 0 6px rgba(255,180,60,0.8), 0 0 14px rgba(255,140,40,0.45)',
            transformOrigin: '50% 100%',
            animation: 'candleFlame 1.6s ease-in-out infinite',
          }} />
        </div>
      )}

      {/* ══ TAP DRIP ══════════════════════════════════════════════════════
        At night the tap sits lower in BathroomDark.png, so spawn point
        drops; vanish point pulls *up* though, since the night sink is
        shallower. --tap-drop-distance overrides the keyframe end value. */}
      <div className="absolute pointer-events-none" style={{
        left: 'calc(50% + 2px)',
        top: `calc(50% + ${isDark ? 24 : 14}px)`,
        zIndex: 15,
        ...(isDark ? { ['--tap-drop-distance' as string]: 'calc(4vh + 4px)' } : {}),
      } as React.CSSProperties}>
        <div className="tap-drop" />
      </div>

      {/* ══ PIXEL EREN ════════════════════════════════════════════════════ */}
      {/* Hidden while sleeping in the bedroom. Body wrapper: squirm while
          being soaped, shake-dry then a happy hop on finish. Idle pauses
          during the finish reaction. */}
      {!isSleeping && (
        <div ref={erenRef} className={cn('absolute transition-all duration-500', done ? 'bottom-[12%]' : 'bottom-[10%]')}
          style={{ left: '50%', transform: 'translateX(-50%)' }}>
          <ErenIdleLayer disabled={scrubbing || reaction.active}>
            <div style={{
              animation: reaction.phase === 'shake' ? 'erenShakeDry 750ms linear'
                : reaction.phase === 'finish' ? 'erenIdleHop 800ms ease-in-out'
                : scrubbing ? 'erenSquirm 400ms steps(2) infinite'
                : undefined,
              transformOrigin: 'bottom center',
            }}>
              {erenSprite}
            </div>
          </ErenIdleLayer>

          {/* Reaction particles + words, anchored to Eren's 200px box. */}
          {scrubbing && scrubWordKey > 0 &&
            <SoundWord key={scrubWordKey} word="SCRUB SCRUB" color={WORD_COLOR.water} left={50} top={2} size={6} />}
          {reaction.phase === 'shake' && <>
            <Droplets bottom="40%" />
            <SoundWord word="SPLASH!" color={WORD_COLOR.water} left={50} top={4} />
          </>}
          {reaction.phase === 'sparkle' && <Sparkles />}
          {reaction.phase === 'finish' && <>
            <Hearts count={2} bottom="58%" />
            <SoundWord word="CLEAN!" color={WORD_COLOR.happy} left={50} top={6} />
          </>}
        </div>
      )}

      {/* ══ SOAP SUDS ═════════════════════════════════════════════════════
        Each bubble fades from 1 → 0 as the current coverage drops
        between its creation coverage and a small anchor near the
        finish threshold. Effect: bubbles wash off individually,
        newest-on-top first, and all are gone before the rinse
        completes (`coverage` ≤ 5). */}
      <div className="absolute inset-0 pointer-events-none z-20">
        {bubbles.map(b => {
          const FADE_ANCHOR = 5
          const range = Math.max(15, b.c - FADE_ANCHOR)
          const op = Math.max(0, Math.min(1, (coverage - FADE_ANCHOR) / range)) * 0.85
          if (op <= 0.01) return null
          return (
            <div key={b.id} className="absolute rounded-full"
              style={{
                left: `${b.x}%`, top: `${b.y}%`, width: b.size, height: b.size,
                transform: 'translate(-50%,-50%)',
                background: 'radial-gradient(circle at 35% 35%, rgba(255,255,255,0.95), rgba(200,230,255,0.6))',
                border: '1px solid rgba(150,200,255,0.5)',
                boxShadow: 'inset 1px 1px 2px rgba(255,255,255,0.8)',
                opacity: op,
                transition: 'opacity 0.25s linear',
              }} />
          )
        })}
      </div>

      {/* ══ SHOWER HEAD ═══════════════════════════════════════════════════ */}
      <div
        ref={showerRef}
        className={cn('absolute z-30', (isSleeping || !showShower) ? 'opacity-0 pointer-events-none' : 'opacity-100', dragShower ? 'cursor-grabbing' : 'cursor-grab')}
        style={{ left: '75%', top: '30%', transform: 'translate(-50%, -50%)', touchAction: 'none' }}
        onPointerDown={onShowerDown}
        onPointerMove={onPointerMove}
        onPointerUp={onShowerUp}
        onTouchStart={stopTouchBubble}
        onTouchMove={stopTouchBubble}
        onTouchEnd={stopTouchBubble}
      >
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-1.5 h-7" style={{ background: 'linear-gradient(180deg, #9ECAE1, #6BAED6)', borderRadius: 3 }} />
        <div className="relative mt-6 flex items-center justify-center"
          style={{ width: 44, height: 18, background: 'linear-gradient(135deg, #AADDF0, #70B8D8)', borderRadius: '4px 4px 10px 10px', border: '2px solid #4A9AB8', boxShadow: '1px 2px 0 #3080A0, inset 0 1px 2px rgba(255,255,255,0.4)' }}>
          <div className="absolute bottom-2 left-0 right-0 flex justify-center gap-1.5">
            {[0,1,2,3,4].map(ni => (
              <div key={ni} className="rounded-full" style={{ width: 3, height: 3, background: 'rgba(30,80,120,0.5)' }} />
            ))}
          </div>
          <div style={{ position: 'absolute', top: 2, left: 4, width: 14, height: 3, background: 'rgba(255,255,255,0.45)', borderRadius: 3 }} />
          {dragShower && (
            <div className="absolute top-full left-1/2 -translate-x-1/2 flex gap-1 pointer-events-none" style={{ marginTop: 2 }}>
              {[0,3,7,11,15].map((ox, si) => (
                <div key={si} className="rounded-full"
                  style={{ width: 2, height: 28 + si * 2, background: 'rgba(100,190,240,0.8)', animation: `fall 0.45s linear ${si * 0.05}s infinite` }} />
              ))}
            </div>
          )}
        </div>
        {showShower && (
          <div className="absolute -bottom-5 left-1/2 -translate-x-1/2 whitespace-nowrap font-pixel text-sky-600" style={{ fontSize: 6 }}>
            {coverage <= 15 ? 'DONE SOON!' : 'DRAG TO RINSE!'}
          </div>
        )}
      </div>

      {/* ══ SOAP BAR ══════════════════════════════════════════════════════ */}
      <div
        ref={soapRef}
        className={cn('absolute z-30', dragSoap ? 'cursor-grabbing scale-110' : 'cursor-grab', (done || isSleeping) && 'opacity-0 pointer-events-none')}
        style={{ left: '12%', top: '62%', transform: 'translate(-50%,-50%)', touchAction: 'none' }}
        onPointerDown={onSoapDown}
        onPointerMove={onPointerMove}
        onPointerUp={onSoapUp}
        onTouchStart={stopTouchBubble}
        onTouchMove={stopTouchBubble}
        onTouchEnd={stopTouchBubble}
      >
        <div className="flex flex-col items-center justify-center"
          style={{ width: 48, height: 30, background: 'linear-gradient(135deg, #FFE4F2 0%, #FF9EC8 45%, #FF6B9D 100%)', borderRadius: 4, border: '2px solid #CC4080', boxShadow: '2px 3px 0 #991A5A' }}>
          <span className="font-pixel text-white/90" style={{ fontSize: 6, letterSpacing: 1 }}>SOAP</span>
          <div className="flex gap-1 mt-0.5">
            {[0,1,2,3].map(k => <div key={k} className="rounded-full" style={{ width: 4, height: 4, background: 'rgba(255,255,255,0.55)', border: '1px solid rgba(255,255,255,0.4)' }} />)}
          </div>
          <div style={{ position: 'absolute', top: 4, left: 5, width: 12, height: 3, background: 'rgba(255,255,255,0.4)', borderRadius: 3 }} />
        </div>
        {!dragSoap && !showShower && (
          <div className="absolute -bottom-5 left-1/2 -translate-x-1/2 whitespace-nowrap font-pixel text-pink-500" style={{ fontSize: 6 }}>
            DRAG ON EREN!
          </div>
        )}
      </div>

      {/* ══ SCENE LABEL ══════════════════════════════════════════════════ */}
      <div className="absolute left-1/2 -translate-x-1/2 z-50" style={{ top: 110 }}>
        <span className="font-pixel text-sky-700 px-3 py-1.5"
          style={{ background: 'linear-gradient(135deg, #E8F8FF, #D0EEFF)', borderRadius: 3, border: '2px solid #A8D4F0', boxShadow: '2px 2px 0 #88B8D8', fontSize: 7 }}>
          BATHROOM
        </span>
      </div>

      {/* ══ TOAST ════════════════════════════════════════════════════════ */}
      {toast && (
        <div className="absolute top-14 left-1/2 -translate-x-1/2 z-50 text-white px-4 py-2.5 animate-float whitespace-nowrap"
          style={{ background: '#1F3A4E', borderRadius: 3, border: '2px solid #3A6A8E', boxShadow: '3px 3px 0 rgba(0,0,0,0.4)', fontFamily: '"Press Start 2P"', fontSize: 7 }}>
          {toast}
        </div>
      )}

      {/* ══ PROGRESS BARS ════════════════════════════════════════════════ */}
      <div className="absolute bottom-4 inset-x-0 px-5 flex flex-col gap-2 items-center pointer-events-none">
        {!done && (
          <div className="w-full max-w-xs pointer-events-none"
            style={{ background: '#1A2A38', borderRadius: 4, border: '2px solid #3A5A70', boxShadow: '3px 3px 0 rgba(0,0,0,0.4)', padding: '10px 12px' }}>
            <div className="flex items-center justify-between mb-1.5">
              <span className="font-pixel text-sky-300" style={{ fontSize: 6 }}>SOAP</span>
              <span className="font-pixel text-sky-400" style={{ fontSize: 6 }}>{Math.round(coverage)}%</span>
            </div>
            <div className="flex gap-0.5 mb-2.5">
              {Array.from({ length: SOAP_SEGMENTS }).map((_, si) => {
                const lit = si < soapFilled
                return (
                  <div key={si} style={{
                    flex: 1, height: 8, borderRadius: 1,
                    background: lit ? '#FF6B9D' : '#2A3A48',
                    border: lit ? '1px solid #FF4080' : '1px solid #3A4A58',
                    boxShadow: lit ? 'inset 0 1px 0 rgba(255,255,255,0.3), 0 0 4px rgba(255,100,160,0.4)' : 'none',
                    transition: 'all 0.15s',
                    transitionDelay: `${si * 20}ms`,
                  }} />
                )
              })}
            </div>
            {showShower && (
              <>
                <div className="flex items-center justify-between mb-1.5">
                  <span className="font-pixel text-sky-300" style={{ fontSize: 6 }}>RINSE</span>
                  <span className="font-pixel text-sky-400" style={{ fontSize: 6 }}>{Math.round(Math.max(0, 100 - coverage))}%</span>
                </div>
                <div className="flex gap-0.5">
                  {Array.from({ length: SOAP_SEGMENTS }).map((_, si) => {
                    const lit = si < rinseFilled
                    return (
                      <div key={si} style={{
                        flex: 1, height: 8, borderRadius: 1,
                        background: lit ? '#6BAED6' : '#2A3A48',
                        border: lit ? '1px solid #4A90BC' : '1px solid #3A4A58',
                        boxShadow: lit ? 'inset 0 1px 0 rgba(255,255,255,0.3), 0 0 4px rgba(100,170,220,0.4)' : 'none',
                        transition: 'all 0.15s',
                        transitionDelay: `${si * 20}ms`,
                      }} />
                    )
                  })}
                </div>
              </>
            )}
            {showShower && !saving && coverage > 10 && (
              <p className="font-pixel text-sky-400 text-center mt-2" style={{ fontSize: 6 }}>DRAG SHOWER TO RINSE!</p>
            )}
            {saving && <p className="font-pixel text-sky-400 text-center mt-2 animate-pulse" style={{ fontSize: 6 }}>SAVING...</p>}
          </div>
        )}
        {done && (
          <div className="w-full max-w-xs pointer-events-auto text-center py-3 active:translate-y-[2px] transition-transform"
            style={{ background: 'linear-gradient(135deg, #50D890, #30C070)', borderRadius: 3, border: '2px solid #20A050', boxShadow: '0 4px 0 #108030', fontFamily: '"Press Start 2P"', fontSize: 8, color: 'white', letterSpacing: 0.5 }}>
            SQUEAKY CLEAN!
          </div>
        )}
      </div>

      <style jsx>{`
        @keyframes fall {
          from { transform: translateY(-4px); opacity: 1; }
          to   { transform: translateY(40px); opacity: 0; }
        }

        .tap-drop {
          position: absolute;
          left: 0;
          top: 0;
          margin-left: -2px;
          width: 4px;
          height: 6px;
          background: linear-gradient(180deg, rgba(200,230,245,0.85) 0%, rgba(110,180,225,0.98) 100%);
          border-radius: 50% 50% 55% 55% / 35% 35% 85% 85%;
          box-shadow:
            0 0 3px rgba(110,180,230,0.7),
            inset 1px 1px 0 rgba(255,255,255,0.7),
            inset -1px -1px 0 rgba(70,140,190,0.25);
          animation: tapDrop 1.6s cubic-bezier(0.45, 0, 0.85, 0.4) infinite;
          transform-origin: top center;
          opacity: 0;
        }
        @keyframes tapDrop {
          0%   { transform: translateY(-3px) scale(0.6, 0.4); opacity: 0; }
          5%   { transform: translateY(0) scale(1, 1); opacity: 1; }
          24%  { transform: translateY(var(--tap-drop-distance, calc(4vh + 7px))) scale(0.85, 1.3); opacity: 1; }
          25%, 100% { transform: translateY(var(--tap-drop-distance, calc(4vh + 7px))) scale(1, 1); opacity: 0; }
        }
      `}</style>

      <LightSwitch targetBottom="12%" targetLeft="50%" persistKey="bathroom" />
    </div>
  )
}
