"""Merge the per-animation manifests the bakers wrote into one generated TS file.

    py scripts/anim_manifest.py

Each baker writes public/anim/<name>.json via anim_lib.write_strip(). This
collects them into src/lib/erenAnim.ts so the playback component imports plain
constants instead of fetching JSON at runtime. Re-run it after any re-bake.

Generated file -- do not hand-edit src/lib/erenAnim.ts.
"""

import glob
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ANIM_DIR = os.path.join(ROOT, 'public', 'anim')
OUT = os.path.join(ROOT, 'src', 'lib', 'erenAnim.ts')

HEAD = '''// GENERATED by scripts/anim_manifest.py from public/anim/*.json -- do not edit.
//
// Baked sprite-animation frame strips for Eren. Each entry describes ONE strip:
// a single row of `frames` equal-sized frames, frame 0 (the resting pose)
// first. SpriteStrip plays it by sliding the row with steps(frames), so the
// sprite animates on real drawn frames instead of a CSS transform on a flat
// PNG.
//
// `rect` is the strip's placement inside the FULL sprite canvas, in percent, so
// an overlay layer (the tail behind the body, the eye band over it) lands
// exactly on the body PNG with no letterbox math. A full-canvas animation (the
// eat poses) is 0/0/100/100.

export interface ErenAnim {
  /** Manifest key, e.g. 'cookTail'. */
  name: string
  /** Public path of the 1-row strip. */
  src: string
  /** Frame count; also the steps() count. */
  frames: number
  /** Full loop length in ms. */
  durationMs: number
  /** 'loop' plays every frame evenly; 'blink' holds frame 0 and flicks. */
  kind: 'loop' | 'blink'
  /** One frame's pixel size inside the strip. */
  frameW: number
  frameH: number
  /** The full sprite canvas [w, h] that `rect` is measured against. */
  canvas: readonly [number, number]
  /** Placement inside that canvas, in percent. */
  rect: { left: number; top: number; width: number; height: number }
  /** The sprite PNG this layer composites over, when it is an overlay. */
  bodySrc: string | null
  /** What the baker did, for whoever reads this next. */
  note: string
}

'''


def main():
    files = sorted(glob.glob(os.path.join(ANIM_DIR, '*.json')))
    entries = []
    for f in files:
        with open(f) as fp:
            m = json.load(fp)
        if m.get('name') == 'smoke':
            continue
        for k in ('name', 'src', 'frames', 'durationMs', 'kind', 'frameW', 'frameH',
                  'canvas', 'rect', 'bodySrc'):
            assert k in m, '%s is missing %s' % (f, k)
        m.setdefault('note', '')
        entries.append(m)
    assert entries, 'no manifests in %s -- run the bakers first' % ANIM_DIR

    lines = [HEAD, 'export const EREN_ANIM = {\n']
    for m in entries:
        r = m['rect']
        lines.append('  %s: {\n' % m['name'])
        lines.append("    name: '%s',\n" % m['name'])
        lines.append("    src: '%s',\n" % m['src'])
        lines.append('    frames: %d,\n' % m['frames'])
        lines.append('    durationMs: %d,\n' % m['durationMs'])
        lines.append("    kind: '%s',\n" % m['kind'])
        lines.append('    frameW: %d,\n' % m['frameW'])
        lines.append('    frameH: %d,\n' % m['frameH'])
        lines.append('    canvas: [%d, %d],\n' % (m['canvas'][0], m['canvas'][1]))
        lines.append('    rect: { left: %s, top: %s, width: %s, height: %s },\n'
                     % (r['left'], r['top'], r['width'], r['height']))
        lines.append('    bodySrc: %s,\n'
                     % ("'%s'" % m['bodySrc'] if m['bodySrc'] else 'null'))
        lines.append("    note: '%s',\n" % str(m['note']).replace("'", "\\'"))
        lines.append('  },\n')
    lines.append('} as const satisfies Record<string, ErenAnim>\n\n')
    lines.append('export type ErenAnimKey = keyof typeof EREN_ANIM\n')

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', newline='\n') as fp:
        fp.write(''.join(lines))
    print('wrote %s' % OUT)
    for m in entries:
        print('  %-10s %2d frames  %5dms  %-5s  %s'
              % (m['name'], m['frames'], m['durationMs'], m['kind'], m['src']))


if __name__ == '__main__':
    main()
