"""Measure each Eren sprite's head box and emit src/lib/headAnchors.ts.

An accessory (crown, hat, medal) has to sit on the head of FORTY-FIVE different
sprites, several of which are hoods or helmets that move the skull somewhere
else entirely. Eyeballing per-skin offsets would be forty-five chances to be
wrong, so this reads the alpha channel instead.

Two numbers per sprite, both in BlinkingEren BOX coordinates (percent of the
square box, after the objectFit:contain letterbox), which is the same space the
eye overlays already use:

  top  topmost opaque row -- where the crown rests
  w    silhouette width just under the crown line -- what the crown scales to

The horizontal CENTRE is deliberately not measured here. It is derived at
render time from the sprite's own eye layout, because a crown belongs over the
face, and an ear or a hood tassel would drag a silhouette midpoint off it.
"""
import json, os, re, sys
from PIL import Image
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUB = os.path.join(ROOT, 'public')
ALPHA = 24            # anything fainter is halo, not sprite
PROBE = 0.18          # fraction of sprite height below the top to measure width


def measure(path):
    im = Image.open(path).convert('RGBA')
    a = np.array(im)[:, :, 3]
    H, W = a.shape
    rows = np.where((a > ALPHA).any(axis=1))[0]
    if len(rows) == 0:
        return None
    top = int(rows[0])
    bot = int(rows[-1])
    span = bot - top
    probe = min(H - 1, top + max(1, int(span * PROBE)))
    seg = np.where(a[probe] > ALPHA)[0]
    if len(seg) == 0:
        return None
    w = int(seg[-1] - seg[0] + 1)

    # Letterbox -> square box, exactly as scripts/build_skins.cjs does it.
    M = max(W, H)
    off_y = (M - H) / 2
    return {
        'top': round(((top + off_y) / M) * 100, 2),
        'w': round((w / M) * 100, 2),
    }


def sprite_paths():
    """Every PNG BlinkingEren is ever handed as `src`."""
    out = []
    # Room / home defaults live at the public root.
    for name in sorted(os.listdir(PUB)):
        if not name.lower().endswith('.png'):
            continue
        if not name.lower().startswith('eren'):
            continue
        out.append('/' + name)
    skins = os.path.join(PUB, 'skins')
    if os.path.isdir(skins):
        for name in sorted(os.listdir(skins)):
            if name.lower().endswith('.png'):
                out.append('/skins/' + name)
    return out


def main():
    table = {}
    missing = []
    for rel in sprite_paths():
        path = os.path.join(PUB, rel.lstrip('/').replace('/', os.sep))
        if not os.path.exists(path):
            missing.append(rel)
            continue
        m = measure(path)
        if m:
            table[rel] = m

    lines = [
        '// AUTO-GENERATED by scripts/measure_heads.py — do not edit by hand.',
        '//',
        '// Where an accessory sits on each sprite, in BlinkingEren BOX',
        '// coordinates (percent of the square box, post-letterbox) — the same',
        '// space the eye overlays use.',
        '//',
        '//   top  topmost opaque row: the line a hat rests on',
        '//   w    silhouette width just below that line: what a hat scales to',
        '//',
        '// The horizontal centre is NOT here. It comes from the sprite\'s own eye',
        '// layout at render time, because a crown belongs over the face and an',
        '// ear would drag a silhouette midpoint off it.',
        '',
        'export interface HeadBox {',
        '  /** % of box height. */',
        '  top: number',
        '  /** % of box width. */',
        '  w: number',
        '}',
        '',
        'export const HEAD_BOXES: Record<string, HeadBox> = {',
    ]
    for k in sorted(table):
        v = table[k]
        lines.append("  '%s': { top: %s, w: %s }," % (k, v['top'], v['w']))
    lines += [
        '}',
        '',
        '/** Fallback for a sprite the measure pass never saw. Averages the set. */',
        'export const DEFAULT_HEAD_BOX: HeadBox = { top: %s, w: %s }' % (
            round(sum(v['top'] for v in table.values()) / max(1, len(table)), 2),
            round(sum(v['w'] for v in table.values()) / max(1, len(table)), 2),
        ),
        '',
        '/** Strips the ?v= cache-buster the skins catalogue appends. */',
        'export function headBox(src: string | undefined): HeadBox {',
        '  if (!src) return DEFAULT_HEAD_BOX',
        '  const clean = src.split(\'?\')[0]',
        '  return HEAD_BOXES[clean] ?? DEFAULT_HEAD_BOX',
        '}',
        '',
    ]
    out = os.path.join(ROOT, 'src', 'lib', 'headAnchors.ts')
    with open(out, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    print('wrote', out, len(table), 'sprites')
    if missing:
        print('missing:', missing)


if __name__ == '__main__':
    main()
