// All 118 elements. This file is intentionally data-only and editable.
//
// Accuracy notes:
//  - `atomicMass` is DISPLAY ONLY and must never be used to generate quiz questions.
//    For elements with no stable isotope, it is the mass number of the most stable /
//    commonly cited isotope (conventionally shown in brackets on printed tables).
//  - `state` is at room temperature (~25 C). Gases: H, He, N, O, F, Ne, Cl, Ar, Kr, Xe,
//    Rn. Liquids: Br, Hg. Everything 1-103 otherwise is solid. The synthetic superheavy
//    elements 104-118 use 'unknown' (their bulk phase has never been measured).
//  - `group` is null for the lanthanides (57-71) and actinides (89-103).
//  - `xpos`/`ypos` drive the CSS grid: main/d-block use xpos=group, ypos=period; the
//    lanthanides sit on ypos 9 and actinides on ypos 10 (both xpos 3-17), i.e. the two
//    separated f-block rows below the main table.

export type ElementCategory =
  | "alkali-metal"
  | "alkaline-earth-metal"
  | "transition-metal"
  | "post-transition-metal"
  | "metalloid"
  | "nonmetal"
  | "halogen"
  | "noble-gas"
  | "lanthanide"
  | "actinide";

export type ElementState = "solid" | "liquid" | "gas" | "unknown";

export interface Element {
  atomicNumber: number;
  symbol: string;
  name: string;
  atomicMass: number; // DISPLAY ONLY — never used in quiz questions
  category: ElementCategory;
  state: ElementState; // at room temperature (~25 C)
  group: number | null; // 1–18, null for lanthanides/actinides
  period: number;
  xpos: number; // grid column 1–18
  ypos: number; // grid row 1–10 (includes the two f-block rows)
  funFact?: string;
  mnemonic?: string;
  nameOrigin?: string;
}

/** Human-readable labels for each category (used by legends/filters). */
export const CATEGORY_LABELS: Record<ElementCategory, string> = {
  "alkali-metal": "Alkali metal",
  "alkaline-earth-metal": "Alkaline earth metal",
  "transition-metal": "Transition metal",
  "post-transition-metal": "Post-transition metal",
  metalloid: "Metalloid",
  nonmetal: "Nonmetal",
  halogen: "Halogen",
  "noble-gas": "Noble gas",
  lanthanide: "Lanthanide",
  actinide: "Actinide",
};

export const elements: Element[] = [
  {
    atomicNumber: 1,
    symbol: "H",
    name: "Hydrogen",
    atomicMass: 1.008,
    category: "nonmetal",
    state: "gas",
    group: 1,
    period: 1,
    xpos: 1,
    ypos: 1,
    funFact:
      "The most abundant element in the universe — about 75% of all normal matter, and the fuel that powers stars.",
    nameOrigin: "From Greek 'hydro' + 'genes', meaning 'water-forming'.",
  },
  {
    atomicNumber: 2,
    symbol: "He",
    name: "Helium",
    atomicMass: 4.0026,
    category: "noble-gas",
    state: "gas",
    group: 18,
    period: 1,
    xpos: 18,
    ypos: 1,
    funFact:
      "Discovered in the Sun's spectrum before it was found on Earth — and it's the only element first detected in space.",
    nameOrigin: "From Greek 'helios', the Sun.",
  },
  {
    atomicNumber: 3,
    symbol: "Li",
    name: "Lithium",
    atomicMass: 6.94,
    category: "alkali-metal",
    state: "solid",
    group: 1,
    period: 2,
    xpos: 1,
    ypos: 2,
    funFact:
      "So light it floats on water (and even on oil) — the lightest metal, now central to rechargeable batteries.",
    nameOrigin: "From Greek 'lithos', meaning 'stone'.",
  },
  {
    atomicNumber: 4,
    symbol: "Be",
    name: "Beryllium",
    atomicMass: 9.0122,
    category: "alkaline-earth-metal",
    state: "solid",
    group: 2,
    period: 2,
    xpos: 2,
    ypos: 2,
    funFact:
      "Transparent to X-rays, so it's used for the windows of X-ray tubes; its dust is highly toxic.",
    nameOrigin: "From the mineral beryl (Greek 'beryllos').",
  },
  {
    atomicNumber: 5,
    symbol: "B",
    name: "Boron",
    atomicMass: 10.81,
    category: "metalloid",
    state: "solid",
    group: 13,
    period: 2,
    xpos: 13,
    ypos: 2,
    funFact:
      "Absorbs neutrons greedily, so it's used in nuclear reactor control rods; also gives borosilicate (Pyrex) glass its heat resistance.",
    nameOrigin: "From the mineral borax, via Arabic 'buraq'.",
  },
  {
    atomicNumber: 6,
    symbol: "C",
    name: "Carbon",
    atomicMass: 12.011,
    category: "nonmetal",
    state: "solid",
    group: 14,
    period: 2,
    xpos: 14,
    ypos: 2,
    funFact:
      "The backbone of all known life, and the same element appears as both soft graphite and the hardest natural material, diamond.",
    nameOrigin: "From Latin 'carbo', meaning 'coal' or 'charcoal'.",
  },
  {
    atomicNumber: 7,
    symbol: "N",
    name: "Nitrogen",
    atomicMass: 14.007,
    category: "nonmetal",
    state: "gas",
    group: 15,
    period: 2,
    xpos: 15,
    ypos: 2,
    funFact:
      "Makes up about 78% of the air you breathe; liquid nitrogen boils at a frosty -196 C.",
    nameOrigin: "From Greek 'nitron' + 'genes', 'niter-forming'.",
  },
  {
    atomicNumber: 8,
    symbol: "O",
    name: "Oxygen",
    atomicMass: 15.999,
    category: "nonmetal",
    state: "gas",
    group: 16,
    period: 2,
    xpos: 16,
    ypos: 2,
    funFact:
      "The most abundant element in Earth's crust by mass, and liquid oxygen is pale blue.",
    nameOrigin: "From Greek 'oxys' + 'genes', meaning 'acid-forming'.",
  },
  {
    atomicNumber: 9,
    symbol: "F",
    name: "Fluorine",
    atomicMass: 18.998,
    category: "halogen",
    state: "gas",
    group: 17,
    period: 2,
    xpos: 17,
    ypos: 2,
    funFact:
      "The most reactive element of all — it even attacks glass and reacts with almost everything.",
    nameOrigin: "From Latin 'fluere', meaning 'to flow' (from the flux fluorite).",
  },
  {
    atomicNumber: 10,
    symbol: "Ne",
    name: "Neon",
    atomicMass: 20.18,
    category: "noble-gas",
    state: "gas",
    group: 18,
    period: 2,
    xpos: 18,
    ypos: 2,
    funFact:
      "Glows a brilliant red-orange when electrified — the original 'neon' sign gas.",
    nameOrigin: "From Greek 'neos', meaning 'new'.",
  },
  {
    atomicNumber: 11,
    symbol: "Na",
    name: "Sodium",
    atomicMass: 22.99,
    category: "alkali-metal",
    state: "solid",
    group: 1,
    period: 3,
    xpos: 1,
    ypos: 3,
    funFact:
      "Soft enough to cut with a knife, it fizzes and can ignite when dropped in water.",
    mnemonic: "Symbol Na = Latin 'NAtrium'. Think table salt: sodium chloride.",
    nameOrigin: "Symbol from Latin 'natrium'; name from English 'soda'.",
  },
  {
    atomicNumber: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomicMass: 24.305,
    category: "alkaline-earth-metal",
    state: "solid",
    group: 2,
    period: 3,
    xpos: 2,
    ypos: 3,
    funFact:
      "Burns with a blinding white light — used in flares, fireworks, and old flash photography.",
    nameOrigin: "From Magnesia, a district in Greece.",
  },
  {
    atomicNumber: 13,
    symbol: "Al",
    name: "Aluminium",
    atomicMass: 26.982,
    category: "post-transition-metal",
    state: "solid",
    group: 13,
    period: 3,
    xpos: 13,
    ypos: 3,
    funFact:
      "Once more precious than gold; Napoleon III reputedly reserved aluminium cutlery for his most honored guests.",
    nameOrigin: "From 'alumina' (Latin 'alumen', alum).",
  },
  {
    atomicNumber: 14,
    symbol: "Si",
    name: "Silicon",
    atomicMass: 28.085,
    category: "metalloid",
    state: "solid",
    group: 14,
    period: 3,
    xpos: 14,
    ypos: 3,
    funFact:
      "The heart of every computer chip — and, as silica/quartz, the main ingredient of sand and glass.",
    mnemonic: "Don't confuse silicon (chips) with silicone (rubbery polymer).",
    nameOrigin: "From Latin 'silex', meaning 'flint'.",
  },
  {
    atomicNumber: 15,
    symbol: "P",
    name: "Phosphorus",
    atomicMass: 30.974,
    category: "nonmetal",
    state: "solid",
    group: 15,
    period: 3,
    xpos: 15,
    ypos: 3,
    funFact:
      "White phosphorus glows in the dark and ignites in air; the first element isolated from urine, in 1669.",
    nameOrigin: "From Greek 'phosphoros', 'light-bearer'.",
  },
  {
    atomicNumber: 16,
    symbol: "S",
    name: "Sulfur",
    atomicMass: 32.06,
    category: "nonmetal",
    state: "solid",
    group: 16,
    period: 3,
    xpos: 16,
    ypos: 3,
    funFact:
      "The bright-yellow 'brimstone' of antiquity; its compounds give rotten eggs and skunks their smell.",
    nameOrigin: "From Latin 'sulphur'.",
  },
  {
    atomicNumber: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomicMass: 35.45,
    category: "halogen",
    state: "gas",
    group: 17,
    period: 3,
    xpos: 17,
    ypos: 3,
    funFact:
      "A choking green-yellow gas used to disinfect drinking water and swimming pools.",
    nameOrigin: "From Greek 'chloros', meaning 'pale green'.",
  },
  {
    atomicNumber: 18,
    symbol: "Ar",
    name: "Argon",
    atomicMass: 39.948,
    category: "noble-gas",
    state: "gas",
    group: 18,
    period: 3,
    xpos: 18,
    ypos: 3,
    funFact:
      "Makes up ~1% of the atmosphere and fills incandescent bulbs so the filament won't burn up.",
    nameOrigin: "From Greek 'argos', meaning 'lazy/inactive'.",
  },
  {
    atomicNumber: 19,
    symbol: "K",
    name: "Potassium",
    atomicMass: 39.098,
    category: "alkali-metal",
    state: "solid",
    group: 1,
    period: 4,
    xpos: 1,
    ypos: 4,
    funFact:
      "Reacts even more violently with water than sodium, bursting into a lilac flame.",
    mnemonic: "Symbol K = Latin 'Kalium' (from al-qalyah, plant ashes / potash).",
    nameOrigin: "Symbol from Latin 'kalium'; name from English 'potash'.",
  },
  {
    atomicNumber: 20,
    symbol: "Ca",
    name: "Calcium",
    atomicMass: 40.078,
    category: "alkaline-earth-metal",
    state: "solid",
    group: 2,
    period: 4,
    xpos: 2,
    ypos: 4,
    funFact:
      "The metal that builds your bones and teeth, and the 'lime' in limestone and chalk.",
    nameOrigin: "From Latin 'calx', meaning 'lime'.",
  },
  {
    atomicNumber: 21,
    symbol: "Sc",
    name: "Scandium",
    atomicMass: 44.956,
    category: "transition-metal",
    state: "solid",
    group: 3,
    period: 4,
    xpos: 3,
    ypos: 4,
    funFact:
      "Added to aluminium to make ultra-strong, lightweight alloys for aerospace and high-end bike frames.",
    nameOrigin: "From 'Scandia', Latin for Scandinavia.",
  },
  {
    atomicNumber: 22,
    symbol: "Ti",
    name: "Titanium",
    atomicMass: 47.867,
    category: "transition-metal",
    state: "solid",
    group: 4,
    period: 4,
    xpos: 4,
    ypos: 4,
    funFact:
      "As strong as steel but ~45% lighter, and so biocompatible it's used for hip and dental implants.",
    nameOrigin: "From the Titans of Greek mythology.",
  },
  {
    atomicNumber: 23,
    symbol: "V",
    name: "Vanadium",
    atomicMass: 50.942,
    category: "transition-metal",
    state: "solid",
    group: 5,
    period: 4,
    xpos: 5,
    ypos: 4,
    funFact:
      "Its compounds come in a rainbow of colors, and a little of it makes the tough steel in tools and engine parts.",
    nameOrigin: "From Vanadis, a name of the Norse goddess Freyja.",
  },
  {
    atomicNumber: 24,
    symbol: "Cr",
    name: "Chromium",
    atomicMass: 51.996,
    category: "transition-metal",
    state: "solid",
    group: 6,
    period: 4,
    xpos: 6,
    ypos: 4,
    funFact:
      "Gives chrome plating its mirror shine and stainless steel its rust resistance; rubies are red from chromium.",
    nameOrigin: "From Greek 'chroma', meaning 'color'.",
  },
  {
    atomicNumber: 25,
    symbol: "Mn",
    name: "Manganese",
    atomicMass: 54.938,
    category: "transition-metal",
    state: "solid",
    group: 7,
    period: 4,
    xpos: 7,
    ypos: 4,
    funFact:
      "Essential for making steel, and the manganese dioxide in everyday alkaline batteries.",
    mnemonic: "Manganese (Mn) vs magnesium (Mg) — Mn has the extra 'n' for maNgaNese.",
    nameOrigin: "From Latin 'magnes', magnet (via the ore magnesia).",
  },
  {
    atomicNumber: 26,
    symbol: "Fe",
    name: "Iron",
    atomicMass: 55.845,
    category: "transition-metal",
    state: "solid",
    group: 8,
    period: 4,
    xpos: 8,
    ypos: 4,
    funFact:
      "Earth's core is mostly iron, and it's the metal in your blood's hemoglobin that carries oxygen.",
    mnemonic: "Symbol Fe = Latin 'FErrum'. Think 'FErromagnetic'.",
    nameOrigin: "Symbol from Latin 'ferrum'; name from Old English 'iren'.",
  },
  {
    atomicNumber: 27,
    symbol: "Co",
    name: "Cobalt",
    atomicMass: 58.933,
    category: "transition-metal",
    state: "solid",
    group: 9,
    period: 4,
    xpos: 9,
    ypos: 4,
    funFact:
      "Gives glass and ceramics their deep 'cobalt blue'; named after mischievous goblins miners blamed for bad ore.",
    nameOrigin: "From German 'kobold', a goblin or evil spirit.",
  },
  {
    atomicNumber: 28,
    symbol: "Ni",
    name: "Nickel",
    atomicMass: 58.693,
    category: "transition-metal",
    state: "solid",
    group: 10,
    period: 4,
    xpos: 10,
    ypos: 4,
    funFact:
      "The US 'nickel' coin is mostly copper; magnets and stainless steel rely on real nickel.",
    nameOrigin: "From German 'Kupfernickel', 'Old Nick's copper' (a deceptive ore).",
  },
  {
    atomicNumber: 29,
    symbol: "Cu",
    name: "Copper",
    atomicMass: 63.546,
    category: "transition-metal",
    state: "solid",
    group: 11,
    period: 4,
    xpos: 11,
    ypos: 4,
    funFact:
      "One of the first metals humans used; its excellent conductivity makes it the standard for electrical wiring.",
    mnemonic: "Symbol Cu = Latin 'CUprum', from Cyprus, famed for copper mines.",
    nameOrigin: "Symbol from Latin 'cuprum' (Cyprus); name from Old English 'coper'.",
  },
  {
    atomicNumber: 30,
    symbol: "Zn",
    name: "Zinc",
    atomicMass: 65.38,
    category: "transition-metal",
    state: "solid",
    group: 12,
    period: 4,
    xpos: 12,
    ypos: 4,
    funFact:
      "Coats steel to stop it rusting (galvanizing) and is an essential nutrient for your immune system.",
    nameOrigin: "From German 'Zink', possibly from 'Zinke', a prong.",
  },
  {
    atomicNumber: 31,
    symbol: "Ga",
    name: "Gallium",
    atomicMass: 69.723,
    category: "post-transition-metal",
    state: "solid",
    group: 13,
    period: 4,
    xpos: 13,
    ypos: 4,
    funFact:
      "Melts at 30 C — a solid metal that turns to liquid in the palm of your hand.",
    nameOrigin: "From 'Gallia', Latin for France.",
  },
  {
    atomicNumber: 32,
    symbol: "Ge",
    name: "Germanium",
    atomicMass: 72.63,
    category: "metalloid",
    state: "solid",
    group: 14,
    period: 4,
    xpos: 14,
    ypos: 4,
    funFact:
      "Powered the first transistors before silicon took over; still used in fiber optics and infrared lenses.",
    nameOrigin: "From 'Germania', Latin for Germany.",
  },
  {
    atomicNumber: 33,
    symbol: "As",
    name: "Arsenic",
    atomicMass: 74.922,
    category: "metalloid",
    state: "solid",
    group: 15,
    period: 4,
    xpos: 15,
    ypos: 4,
    funFact:
      "The infamous 'inheritance powder' poison of history — odorless, tasteless, and deadly.",
    nameOrigin: "From Greek 'arsenikon', a yellow pigment.",
  },
  {
    atomicNumber: 34,
    symbol: "Se",
    name: "Selenium",
    atomicMass: 78.971,
    category: "nonmetal",
    state: "solid",
    group: 16,
    period: 4,
    xpos: 16,
    ypos: 4,
    funFact:
      "Its electrical resistance drops in light, which made it the basis of early photocopiers and light meters.",
    nameOrigin: "From Greek 'selene', the Moon.",
  },
  {
    atomicNumber: 35,
    symbol: "Br",
    name: "Bromine",
    atomicMass: 79.904,
    category: "halogen",
    state: "liquid",
    group: 17,
    period: 4,
    xpos: 17,
    ypos: 4,
    funFact:
      "One of only two elements that's a liquid at room temperature — a dense, red-brown, foul-smelling one.",
    nameOrigin: "From Greek 'bromos', meaning 'stench'.",
  },
  {
    atomicNumber: 36,
    symbol: "Kr",
    name: "Krypton",
    atomicMass: 83.798,
    category: "noble-gas",
    state: "gas",
    group: 18,
    period: 4,
    xpos: 18,
    ypos: 4,
    funFact:
      "Real, but harmless — used in high-performance lighting; the metre was once defined by a krypton spectral line.",
    nameOrigin: "From Greek 'kryptos', meaning 'hidden'.",
  },
  {
    atomicNumber: 37,
    symbol: "Rb",
    name: "Rubidium",
    atomicMass: 85.468,
    category: "alkali-metal",
    state: "solid",
    group: 1,
    period: 5,
    xpos: 1,
    ypos: 5,
    funFact:
      "So reactive it ignites instantly in air; used in some atomic clocks.",
    nameOrigin: "From Latin 'rubidus', 'deepest red' (its spectral lines).",
  },
  {
    atomicNumber: 38,
    symbol: "Sr",
    name: "Strontium",
    atomicMass: 87.62,
    category: "alkaline-earth-metal",
    state: "solid",
    group: 2,
    period: 5,
    xpos: 2,
    ypos: 5,
    funFact:
      "Burns bright crimson — it's what gives red fireworks and emergency flares their color.",
    nameOrigin: "From Strontian, a village in Scotland where its ore was found.",
  },
  {
    atomicNumber: 39,
    symbol: "Y",
    name: "Yttrium",
    atomicMass: 88.906,
    category: "transition-metal",
    state: "solid",
    group: 3,
    period: 5,
    xpos: 3,
    ypos: 5,
    funFact:
      "Used in the red phosphors of old color TVs and in superconductors and LED bulbs.",
    nameOrigin: "From Ytterby, a Swedish village that named four elements.",
  },
  {
    atomicNumber: 40,
    symbol: "Zr",
    name: "Zirconium",
    atomicMass: 91.224,
    category: "transition-metal",
    state: "solid",
    group: 4,
    period: 5,
    xpos: 4,
    ypos: 5,
    funFact:
      "Barely absorbs neutrons, so it sheathes nuclear fuel rods; cubic zirconia mimics diamond.",
    nameOrigin: "From the gemstone zircon, via Persian 'zargun', 'gold-colored'.",
  },
  {
    atomicNumber: 41,
    symbol: "Nb",
    name: "Niobium",
    atomicMass: 92.906,
    category: "transition-metal",
    state: "solid",
    group: 5,
    period: 5,
    xpos: 5,
    ypos: 5,
    funFact:
      "A key metal in superconducting magnets, including those in MRI scanners and particle accelerators.",
    nameOrigin: "From Niobe, daughter of Tantalus in Greek myth (next to tantalum).",
  },
  {
    atomicNumber: 42,
    symbol: "Mo",
    name: "Molybdenum",
    atomicMass: 95.95,
    category: "transition-metal",
    state: "solid",
    group: 6,
    period: 5,
    xpos: 6,
    ypos: 5,
    funFact:
      "Has one of the highest melting points of all metals; adds strength and heat resistance to steel.",
    nameOrigin: "From Greek 'molybdos', meaning 'lead' (it was confused with lead ore).",
  },
  {
    atomicNumber: 43,
    symbol: "Tc",
    name: "Technetium",
    atomicMass: 98,
    category: "transition-metal",
    state: "solid",
    group: 7,
    period: 5,
    xpos: 7,
    ypos: 5,
    funFact:
      "The first artificially produced element, and the lightest with no stable isotope; vital in medical imaging.",
    nameOrigin: "From Greek 'technetos', meaning 'artificial'.",
  },
  {
    atomicNumber: 44,
    symbol: "Ru",
    name: "Ruthenium",
    atomicMass: 101.07,
    category: "transition-metal",
    state: "solid",
    group: 8,
    period: 5,
    xpos: 8,
    ypos: 5,
    funFact:
      "A hard platinum-group metal that hardens electrical contacts and coats hard-disk platters.",
    nameOrigin: "From 'Ruthenia', Latin for Russia.",
  },
  {
    atomicNumber: 45,
    symbol: "Rh",
    name: "Rhodium",
    atomicMass: 102.91,
    category: "transition-metal",
    state: "solid",
    group: 9,
    period: 5,
    xpos: 9,
    ypos: 5,
    funFact:
      "Often the most expensive precious metal; the catalytic heart of car exhaust converters.",
    nameOrigin: "From Greek 'rhodon', meaning 'rose' (its salts are rose-red).",
  },
  {
    atomicNumber: 46,
    symbol: "Pd",
    name: "Palladium",
    atomicMass: 106.42,
    category: "transition-metal",
    state: "solid",
    group: 10,
    period: 5,
    xpos: 10,
    ypos: 5,
    funFact:
      "Can soak up many times its own volume in hydrogen gas, like a metallic sponge.",
    nameOrigin: "Named after the asteroid Pallas, discovered around the same time.",
  },
  {
    atomicNumber: 47,
    symbol: "Ag",
    name: "Silver",
    atomicMass: 107.87,
    category: "transition-metal",
    state: "solid",
    group: 11,
    period: 5,
    xpos: 11,
    ypos: 5,
    funFact:
      "The best electrical and thermal conductor of any element, and naturally antimicrobial.",
    mnemonic: "Symbol Ag = Latin 'ARGentum'. Think Argentina, 'land of silver'.",
    nameOrigin: "Symbol from Latin 'argentum'; name from Old English 'seolfor'.",
  },
  {
    atomicNumber: 48,
    symbol: "Cd",
    name: "Cadmium",
    atomicMass: 112.41,
    category: "transition-metal",
    state: "solid",
    group: 12,
    period: 5,
    xpos: 12,
    ypos: 5,
    funFact:
      "Gives 'cadmium yellow' artist's paint its vivid color, but is quite toxic; once common in rechargeable NiCd batteries.",
    nameOrigin: "From 'cadmia', the Latin name for calamine (zinc ore).",
  },
  {
    atomicNumber: 49,
    symbol: "In",
    name: "Indium",
    atomicMass: 114.82,
    category: "post-transition-metal",
    state: "solid",
    group: 13,
    period: 5,
    xpos: 13,
    ypos: 5,
    funFact:
      "So soft it leaves a mark on paper; the indium tin oxide in touchscreens is transparent yet conducts electricity.",
    nameOrigin: "From the indigo-blue line in its emission spectrum.",
  },
  {
    atomicNumber: 50,
    symbol: "Sn",
    name: "Tin",
    atomicMass: 118.71,
    category: "post-transition-metal",
    state: "solid",
    group: 14,
    period: 5,
    xpos: 14,
    ypos: 5,
    funFact:
      "A bar of tin emits a faint crackle, the 'tin cry', when bent. Alloyed with copper it makes bronze.",
    mnemonic: "Symbol Sn = Latin 'StaNnum'.",
    nameOrigin: "Symbol from Latin 'stannum'; name from Old English 'tin'.",
  },
  {
    atomicNumber: 51,
    symbol: "Sb",
    name: "Antimony",
    atomicMass: 121.76,
    category: "metalloid",
    state: "solid",
    group: 15,
    period: 5,
    xpos: 15,
    ypos: 5,
    funFact:
      "Used since antiquity as the eye cosmetic 'kohl'; today it's a flame retardant.",
    mnemonic: "Symbol Sb = Latin 'StiBium' (the ancient eye-paint stibnite).",
    nameOrigin: "Symbol from Latin 'stibium'; name possibly 'anti-monos', 'not alone'.",
  },
  {
    atomicNumber: 52,
    symbol: "Te",
    name: "Tellurium",
    atomicMass: 127.6,
    category: "metalloid",
    state: "solid",
    group: 16,
    period: 5,
    xpos: 16,
    ypos: 5,
    funFact:
      "Eating even a trace gives you garlic breath for weeks; used in solar panels and rewritable discs.",
    nameOrigin: "From Latin 'tellus', meaning 'earth'.",
  },
  {
    atomicNumber: 53,
    symbol: "I",
    name: "Iodine",
    atomicMass: 126.9,
    category: "halogen",
    state: "solid",
    group: 17,
    period: 5,
    xpos: 17,
    ypos: 5,
    funFact:
      "Sublimes into a striking violet vapor; added to table salt to prevent thyroid disease.",
    nameOrigin: "From Greek 'iodes', meaning 'violet'.",
  },
  {
    atomicNumber: 54,
    symbol: "Xe",
    name: "Xenon",
    atomicMass: 131.29,
    category: "noble-gas",
    state: "gas",
    group: 18,
    period: 5,
    xpos: 18,
    ypos: 5,
    funFact:
      "Powers car HID headlights and camera flashes, and is used as a (rare) anesthetic and ion-engine propellant.",
    nameOrigin: "From Greek 'xenos', meaning 'stranger'.",
  },
  {
    atomicNumber: 55,
    symbol: "Cs",
    name: "Caesium",
    atomicMass: 132.91,
    category: "alkali-metal",
    state: "solid",
    group: 1,
    period: 6,
    xpos: 1,
    ypos: 6,
    funFact:
      "The 'tick' of the atomic clock: one second is defined by 9,192,631,770 vibrations of a caesium atom.",
    nameOrigin: "From Latin 'caesius', 'sky-blue' (its spectral lines).",
  },
  {
    atomicNumber: 56,
    symbol: "Ba",
    name: "Barium",
    atomicMass: 137.33,
    category: "alkaline-earth-metal",
    state: "solid",
    group: 2,
    period: 6,
    xpos: 2,
    ypos: 6,
    funFact:
      "You drink a 'barium meal' so your digestive tract shows up on X-rays; it also makes green fireworks.",
    nameOrigin: "From Greek 'barys', meaning 'heavy'.",
  },
  {
    atomicNumber: 57,
    symbol: "La",
    name: "Lanthanum",
    atomicMass: 138.91,
    category: "lanthanide",
    state: "solid",
    group: null,
    period: 6,
    xpos: 3,
    ypos: 9,
    funFact:
      "Gives the lanthanide series its name; used in camera lenses and old hybrid-car batteries.",
    nameOrigin: "From Greek 'lanthanein', meaning 'to lie hidden'.",
  },
  {
    atomicNumber: 58,
    symbol: "Ce",
    name: "Cerium",
    atomicMass: 140.12,
    category: "lanthanide",
    state: "solid",
    group: null,
    period: 6,
    xpos: 4,
    ypos: 9,
    funFact:
      "The most abundant rare-earth element; the spark in cigarette-lighter flints is cerium alloy.",
    nameOrigin: "Named after Ceres, the dwarf planet discovered just before it.",
  },
  {
    atomicNumber: 59,
    symbol: "Pr",
    name: "Praseodymium",
    atomicMass: 140.91,
    category: "lanthanide",
    state: "solid",
    group: null,
    period: 6,
    xpos: 5,
    ypos: 9,
    funFact:
      "Tints welders' and glassblowers' goggles green and helps make powerful magnets.",
    nameOrigin: "From Greek 'prasios didymos', 'green twin'.",
  },
  {
    atomicNumber: 60,
    symbol: "Nd",
    name: "Neodymium",
    atomicMass: 144.24,
    category: "lanthanide",
    state: "solid",
    group: null,
    period: 6,
    xpos: 6,
    ypos: 9,
    funFact:
      "Makes the strongest permanent magnets known — in headphones, hard drives, and wind turbines.",
    nameOrigin: "From Greek 'neos didymos', 'new twin'.",
  },
  {
    atomicNumber: 61,
    symbol: "Pm",
    name: "Promethium",
    atomicMass: 145,
    category: "lanthanide",
    state: "solid",
    group: null,
    period: 6,
    xpos: 7,
    ypos: 9,
    funFact:
      "The only radioactive lanthanide with no stable isotope; once used in glow-in-the-dark watch dials.",
    nameOrigin: "From Prometheus, who stole fire for humanity in Greek myth.",
  },
  {
    atomicNumber: 62,
    symbol: "Sm",
    name: "Samarium",
    atomicMass: 150.36,
    category: "lanthanide",
    state: "solid",
    group: null,
    period: 6,
    xpos: 8,
    ypos: 9,
    funFact:
      "Samarium-cobalt magnets keep their strength at high temperatures, useful in aerospace.",
    nameOrigin: "From the mineral samarskite, named after a Russian official, Samarsky.",
  },
  {
    atomicNumber: 63,
    symbol: "Eu",
    name: "Europium",
    atomicMass: 151.96,
    category: "lanthanide",
    state: "solid",
    group: null,
    period: 6,
    xpos: 9,
    ypos: 9,
    funFact:
      "The red and blue phosphors in screens and the anti-counterfeit glow in euro banknotes.",
    nameOrigin: "Named after the continent of Europe.",
  },
  {
    atomicNumber: 64,
    symbol: "Gd",
    name: "Gadolinium",
    atomicMass: 157.25,
    category: "lanthanide",
    state: "solid",
    group: null,
    period: 6,
    xpos: 10,
    ypos: 9,
    funFact:
      "Injected as a contrast agent to brighten MRI scans, thanks to its strong magnetism.",
    nameOrigin: "Named after chemist Johan Gadolin.",
  },
  {
    atomicNumber: 65,
    symbol: "Tb",
    name: "Terbium",
    atomicMass: 158.93,
    category: "lanthanide",
    state: "solid",
    group: null,
    period: 6,
    xpos: 11,
    ypos: 9,
    funFact:
      "Provides the green glow in displays and fluorescent lamps.",
    nameOrigin: "From Ytterby, the Swedish village (also y/yb/er).",
  },
  {
    atomicNumber: 66,
    symbol: "Dy",
    name: "Dysprosium",
    atomicMass: 162.5,
    category: "lanthanide",
    state: "solid",
    group: null,
    period: 6,
    xpos: 12,
    ypos: 9,
    funFact:
      "Added to magnets so they keep working at the high heat inside electric-car motors.",
    nameOrigin: "From Greek 'dysprositos', meaning 'hard to get at'.",
  },
  {
    atomicNumber: 67,
    symbol: "Ho",
    name: "Holmium",
    atomicMass: 164.93,
    category: "lanthanide",
    state: "solid",
    group: null,
    period: 6,
    xpos: 13,
    ypos: 9,
    funFact:
      "Has the highest magnetic strength of any element, and powers precise surgical lasers.",
    nameOrigin: "From 'Holmia', Latin for Stockholm.",
  },
  {
    atomicNumber: 68,
    symbol: "Er",
    name: "Erbium",
    atomicMass: 167.26,
    category: "lanthanide",
    state: "solid",
    group: null,
    period: 6,
    xpos: 14,
    ypos: 9,
    funFact:
      "Amplifies light in the fiber-optic cables that carry the internet across oceans.",
    nameOrigin: "From Ytterby, the Swedish village.",
  },
  {
    atomicNumber: 69,
    symbol: "Tm",
    name: "Thulium",
    atomicMass: 168.93,
    category: "lanthanide",
    state: "solid",
    group: null,
    period: 6,
    xpos: 15,
    ypos: 9,
    funFact:
      "The rarest stable lanthanide; used in portable X-ray sources and some lasers.",
    nameOrigin: "From 'Thule', a mythical land in the far north.",
  },
  {
    atomicNumber: 70,
    symbol: "Yb",
    name: "Ytterbium",
    atomicMass: 173.05,
    category: "lanthanide",
    state: "solid",
    group: null,
    period: 6,
    xpos: 16,
    ypos: 9,
    funFact:
      "Powers some of the most accurate optical atomic clocks ever built.",
    nameOrigin: "From Ytterby, the Swedish village.",
  },
  {
    atomicNumber: 71,
    symbol: "Lu",
    name: "Lutetium",
    atomicMass: 174.97,
    category: "lanthanide",
    state: "solid",
    group: null,
    period: 6,
    xpos: 17,
    ypos: 9,
    funFact:
      "The densest and hardest lanthanide; used in PET-scan detectors and oil-refining catalysts.",
    nameOrigin: "From 'Lutetia', the Roman name for Paris.",
  },
  {
    atomicNumber: 72,
    symbol: "Hf",
    name: "Hafnium",
    atomicMass: 178.49,
    category: "transition-metal",
    state: "solid",
    group: 4,
    period: 6,
    xpos: 4,
    ypos: 6,
    funFact:
      "Absorbs neutrons so well it makes nuclear-submarine control rods; vital in modern computer-chip insulators.",
    nameOrigin: "From 'Hafnia', Latin for Copenhagen.",
  },
  {
    atomicNumber: 73,
    symbol: "Ta",
    name: "Tantalum",
    atomicMass: 180.95,
    category: "transition-metal",
    state: "solid",
    group: 5,
    period: 6,
    xpos: 5,
    ypos: 6,
    funFact:
      "Corrosion-proof and body-friendly, it forms the tiny capacitors inside nearly every phone.",
    nameOrigin: "From Tantalus of Greek myth, condemned to eternal thirst.",
  },
  {
    atomicNumber: 74,
    symbol: "W",
    name: "Tungsten",
    atomicMass: 183.84,
    category: "transition-metal",
    state: "solid",
    group: 6,
    period: 6,
    xpos: 6,
    ypos: 6,
    funFact:
      "Has the highest melting point of all metals (3,422 C) — the glowing filament in old light bulbs.",
    mnemonic: "Symbol W = 'Wolfram', its German name (the ore 'wolf's froth').",
    nameOrigin: "Name from Swedish 'tung sten', 'heavy stone'; symbol from 'wolfram'.",
  },
  {
    atomicNumber: 75,
    symbol: "Re",
    name: "Rhenium",
    atomicMass: 186.21,
    category: "transition-metal",
    state: "solid",
    group: 7,
    period: 6,
    xpos: 7,
    ypos: 6,
    funFact:
      "One of the rarest elements in Earth's crust; its heat resistance is prized in jet-engine turbine blades.",
    nameOrigin: "From 'Rhenus', Latin for the river Rhine.",
  },
  {
    atomicNumber: 76,
    symbol: "Os",
    name: "Osmium",
    atomicMass: 190.23,
    category: "transition-metal",
    state: "solid",
    group: 8,
    period: 6,
    xpos: 8,
    ypos: 6,
    funFact:
      "The densest naturally occurring element — twice as dense as lead; once tipped fountain pens.",
    nameOrigin: "From Greek 'osme', meaning 'smell' (its oxide stinks).",
  },
  {
    atomicNumber: 77,
    symbol: "Ir",
    name: "Iridium",
    atomicMass: 192.22,
    category: "transition-metal",
    state: "solid",
    group: 9,
    period: 6,
    xpos: 9,
    ypos: 6,
    funFact:
      "A worldwide iridium-rich clay layer is key evidence that an asteroid killed the dinosaurs.",
    nameOrigin: "From Latin 'iris', the rainbow (its salts are multicolored).",
  },
  {
    atomicNumber: 78,
    symbol: "Pt",
    name: "Platinum",
    atomicMass: 195.08,
    category: "transition-metal",
    state: "solid",
    group: 10,
    period: 6,
    xpos: 10,
    ypos: 6,
    funFact:
      "So unreactive and rare it symbolizes luxury, and it catalyzes reactions in car exhaust converters.",
    nameOrigin: "From Spanish 'platina', 'little silver'.",
  },
  {
    atomicNumber: 79,
    symbol: "Au",
    name: "Gold",
    atomicMass: 196.97,
    category: "transition-metal",
    state: "solid",
    group: 11,
    period: 6,
    xpos: 11,
    ypos: 6,
    funFact:
      "So malleable that one gram can be beaten into a sheet a square meter wide; it never tarnishes.",
    mnemonic: "Symbol Au = Latin 'AUrum', 'shining dawn'. ('Ay, you found gold!')",
    nameOrigin: "Symbol from Latin 'aurum'; name from Old English 'gold'.",
  },
  {
    atomicNumber: 80,
    symbol: "Hg",
    name: "Mercury",
    atomicMass: 200.59,
    category: "transition-metal",
    state: "liquid",
    group: 12,
    period: 6,
    xpos: 12,
    ypos: 6,
    funFact:
      "The only metal that's liquid at room temperature — 'quicksilver' that beads up and rolls.",
    mnemonic: "Symbol Hg = Latin 'HydrarGyrum', Greek for 'water-silver' (liquid metal).",
    nameOrigin: "Symbol from Latin 'hydrargyrum'; name from the planet/god Mercury.",
  },
  {
    atomicNumber: 81,
    symbol: "Tl",
    name: "Thallium",
    atomicMass: 204.38,
    category: "post-transition-metal",
    state: "solid",
    group: 13,
    period: 6,
    xpos: 13,
    ypos: 6,
    funFact:
      "A colorless, tasteless poison once called 'the poisoner's poison'; now tightly controlled.",
    nameOrigin: "From Greek 'thallos', 'green shoot' (its bright green spectral line).",
  },
  {
    atomicNumber: 82,
    symbol: "Pb",
    name: "Lead",
    atomicMass: 207.2,
    category: "post-transition-metal",
    state: "solid",
    group: 14,
    period: 6,
    xpos: 14,
    ypos: 6,
    funFact:
      "Dense and soft, the Romans used it for water pipes — the root of the word 'plumbing'.",
    mnemonic: "Symbol Pb = Latin 'PlumBum'; Roman plumbers used lead pipes.",
    nameOrigin: "Symbol from Latin 'plumbum'; name from Old English 'lead'.",
  },
  {
    atomicNumber: 83,
    symbol: "Bi",
    name: "Bismuth",
    atomicMass: 208.98,
    category: "post-transition-metal",
    state: "solid",
    group: 15,
    period: 6,
    xpos: 15,
    ypos: 6,
    funFact:
      "Forms dazzling rainbow, staircase-like crystals, and is the active ingredient in Pepto-Bismol.",
    nameOrigin: "From German 'Wismut', possibly 'white mass'.",
  },
  {
    atomicNumber: 84,
    symbol: "Po",
    name: "Polonium",
    atomicMass: 209,
    category: "post-transition-metal",
    state: "solid",
    group: 16,
    period: 6,
    xpos: 16,
    ypos: 6,
    funFact:
      "Intensely radioactive — it glows blue and was used to poison ex-spy Alexander Litvinenko.",
    nameOrigin: "Named by Marie Curie after her homeland, Poland.",
  },
  {
    atomicNumber: 85,
    symbol: "At",
    name: "Astatine",
    atomicMass: 210,
    category: "halogen",
    state: "solid",
    group: 17,
    period: 6,
    xpos: 17,
    ypos: 6,
    funFact:
      "The rarest naturally occurring element — perhaps less than a gram exists in Earth's crust at any time.",
    nameOrigin: "From Greek 'astatos', meaning 'unstable'.",
  },
  {
    atomicNumber: 86,
    symbol: "Rn",
    name: "Radon",
    atomicMass: 222,
    category: "noble-gas",
    state: "gas",
    group: 18,
    period: 6,
    xpos: 18,
    ypos: 6,
    funFact:
      "A radioactive gas that seeps from the ground into basements — a leading cause of lung cancer in non-smokers.",
    nameOrigin: "Named after radium, from which it forms by decay.",
  },
  {
    atomicNumber: 87,
    symbol: "Fr",
    name: "Francium",
    atomicMass: 223,
    category: "alkali-metal",
    state: "solid",
    group: 1,
    period: 7,
    xpos: 1,
    ypos: 7,
    funFact:
      "So rare and unstable that fewer than 30 grams exist on Earth at any moment; the most reactive metal.",
    nameOrigin: "Named after France, by its discoverer Marguerite Perey.",
  },
  {
    atomicNumber: 88,
    symbol: "Ra",
    name: "Radium",
    atomicMass: 226,
    category: "alkaline-earth-metal",
    state: "solid",
    group: 2,
    period: 7,
    xpos: 2,
    ypos: 7,
    funFact:
      "Glows in the dark and was once painted on watch dials — until the deadly 'Radium Girls' tragedy.",
    nameOrigin: "From Latin 'radius', a ray (of its radioactivity).",
  },
  {
    atomicNumber: 89,
    symbol: "Ac",
    name: "Actinium",
    atomicMass: 227,
    category: "actinide",
    state: "solid",
    group: null,
    period: 7,
    xpos: 3,
    ypos: 10,
    funFact:
      "Glows pale blue in the dark from its own intense radioactivity; gives the actinide series its name.",
    nameOrigin: "From Greek 'aktis', meaning 'ray' or 'beam'.",
  },
  {
    atomicNumber: 90,
    symbol: "Th",
    name: "Thorium",
    atomicMass: 232.04,
    category: "actinide",
    state: "solid",
    group: null,
    period: 7,
    xpos: 4,
    ypos: 10,
    funFact:
      "A potential nuclear fuel that's far more abundant than uranium; once used in gas-lantern mantles.",
    nameOrigin: "Named after Thor, the Norse god of thunder.",
  },
  {
    atomicNumber: 91,
    symbol: "Pa",
    name: "Protactinium",
    atomicMass: 231.04,
    category: "actinide",
    state: "solid",
    group: null,
    period: 7,
    xpos: 5,
    ypos: 10,
    funFact:
      "One of the rarest and most expensive natural elements; it decays into actinium.",
    nameOrigin: "From Greek 'protos' + actinium, 'parent of actinium'.",
  },
  {
    atomicNumber: 92,
    symbol: "U",
    name: "Uranium",
    atomicMass: 238.03,
    category: "actinide",
    state: "solid",
    group: null,
    period: 7,
    xpos: 6,
    ypos: 10,
    funFact:
      "The heaviest naturally abundant element; its fission powers nuclear reactors and atomic bombs.",
    nameOrigin: "Named after the planet Uranus, discovered a few years earlier.",
  },
  {
    atomicNumber: 93,
    symbol: "Np",
    name: "Neptunium",
    atomicMass: 237,
    category: "actinide",
    state: "solid",
    group: null,
    period: 7,
    xpos: 7,
    ypos: 10,
    funFact:
      "The first synthetic transuranium element, made by bombarding uranium with neutrons.",
    nameOrigin: "Named after Neptune, the planet beyond Uranus.",
  },
  {
    atomicNumber: 94,
    symbol: "Pu",
    name: "Plutonium",
    atomicMass: 244,
    category: "actinide",
    state: "solid",
    group: null,
    period: 7,
    xpos: 8,
    ypos: 10,
    funFact:
      "Warm to the touch from its own radioactivity; powers spacecraft like the Voyager probes and Mars rovers.",
    nameOrigin: "Named after Pluto, continuing the planetary sequence.",
  },
  {
    atomicNumber: 95,
    symbol: "Am",
    name: "Americium",
    atomicMass: 243,
    category: "actinide",
    state: "solid",
    group: null,
    period: 7,
    xpos: 9,
    ypos: 10,
    funFact:
      "Sits inside most household smoke detectors, where it ionizes air to sense smoke.",
    nameOrigin: "Named after the Americas.",
  },
  {
    atomicNumber: 96,
    symbol: "Cm",
    name: "Curium",
    atomicMass: 247,
    category: "actinide",
    state: "solid",
    group: null,
    period: 7,
    xpos: 10,
    ypos: 10,
    funFact:
      "Glows red-purple in the dark and has powered instruments on Mars rovers.",
    nameOrigin: "Named after Marie and Pierre Curie.",
  },
  {
    atomicNumber: 97,
    symbol: "Bk",
    name: "Berkelium",
    atomicMass: 247,
    category: "actinide",
    state: "solid",
    group: null,
    period: 7,
    xpos: 11,
    ypos: 10,
    funFact:
      "So scarce that the target used to discover element 117 took years of production to make.",
    nameOrigin: "Named after Berkeley, California, where it was first made.",
  },
  {
    atomicNumber: 98,
    symbol: "Cf",
    name: "Californium",
    atomicMass: 251,
    category: "actinide",
    state: "solid",
    group: null,
    period: 7,
    xpos: 12,
    ypos: 10,
    funFact:
      "A powerful neutron emitter used to start up nuclear reactors and scan for gold and oil.",
    nameOrigin: "Named after California and its university.",
  },
  {
    atomicNumber: 99,
    symbol: "Es",
    name: "Einsteinium",
    atomicMass: 252,
    category: "actinide",
    state: "solid",
    group: null,
    period: 7,
    xpos: 13,
    ypos: 10,
    funFact:
      "Discovered in the debris of the first hydrogen-bomb test in 1952.",
    nameOrigin: "Named after Albert Einstein.",
  },
  {
    atomicNumber: 100,
    symbol: "Fm",
    name: "Fermium",
    atomicMass: 257,
    category: "actinide",
    state: "solid",
    group: null,
    period: 7,
    xpos: 14,
    ypos: 10,
    funFact:
      "The heaviest element that can be made by neutron bombardment; also found in 1952 H-bomb fallout.",
    nameOrigin: "Named after physicist Enrico Fermi.",
  },
  {
    atomicNumber: 101,
    symbol: "Md",
    name: "Mendelevium",
    atomicMass: 258,
    category: "actinide",
    state: "solid",
    group: null,
    period: 7,
    xpos: 15,
    ypos: 10,
    funFact:
      "First made one atom at a time — the discovery rested on just 17 atoms.",
    nameOrigin: "Named after Dmitri Mendeleev, father of the periodic table.",
  },
  {
    atomicNumber: 102,
    symbol: "No",
    name: "Nobelium",
    atomicMass: 259,
    category: "actinide",
    state: "solid",
    group: null,
    period: 7,
    xpos: 16,
    ypos: 10,
    funFact:
      "Its discovery was claimed by rival labs in a Cold-War priority dispute.",
    nameOrigin: "Named after Alfred Nobel.",
  },
  {
    atomicNumber: 103,
    symbol: "Lr",
    name: "Lawrencium",
    atomicMass: 262,
    category: "actinide",
    state: "solid",
    group: null,
    period: 7,
    xpos: 17,
    ypos: 10,
    funFact:
      "The final actinide; only a few atoms have ever been made, lasting mere seconds.",
    nameOrigin: "Named after Ernest Lawrence, inventor of the cyclotron.",
  },
  {
    atomicNumber: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    atomicMass: 267,
    category: "transition-metal",
    state: "unknown",
    group: 4,
    period: 7,
    xpos: 4,
    ypos: 7,
    funFact:
      "The first transactinide ('superheavy') element; its most stable isotopes last only hours.",
    nameOrigin: "Named after physicist Ernest Rutherford.",
  },
  {
    atomicNumber: 105,
    symbol: "Db",
    name: "Dubnium",
    atomicMass: 268,
    category: "transition-metal",
    state: "unknown",
    group: 5,
    period: 7,
    xpos: 5,
    ypos: 7,
    funFact:
      "Exists only as a few fleeting atoms made in particle accelerators.",
    nameOrigin: "Named after Dubna, Russia, home of a major nuclear lab.",
  },
  {
    atomicNumber: 106,
    symbol: "Sg",
    name: "Seaborgium",
    atomicMass: 269,
    category: "transition-metal",
    state: "unknown",
    group: 6,
    period: 7,
    xpos: 6,
    ypos: 7,
    funFact:
      "One of the few elements named after a person who was alive at the time, Glenn Seaborg.",
    nameOrigin: "Named after nuclear chemist Glenn T. Seaborg.",
  },
  {
    atomicNumber: 107,
    symbol: "Bh",
    name: "Bohrium",
    atomicMass: 270,
    category: "transition-metal",
    state: "unknown",
    group: 7,
    period: 7,
    xpos: 7,
    ypos: 7,
    funFact:
      "Only a handful of atoms have ever existed, each lasting a fraction of a second.",
    nameOrigin: "Named after physicist Niels Bohr.",
  },
  {
    atomicNumber: 108,
    symbol: "Hs",
    name: "Hassium",
    atomicMass: 269,
    category: "transition-metal",
    state: "unknown",
    group: 8,
    period: 7,
    xpos: 8,
    ypos: 7,
    funFact:
      "Chemistry on just a few atoms suggests it behaves like a heavier cousin of osmium.",
    nameOrigin: "From 'Hassia', Latin for the German state of Hesse.",
  },
  {
    atomicNumber: 109,
    symbol: "Mt",
    name: "Meitnerium",
    atomicMass: 278,
    category: "transition-metal",
    state: "unknown",
    group: 9,
    period: 7,
    xpos: 9,
    ypos: 7,
    funFact:
      "Named for a pioneer of nuclear fission who was overlooked for the Nobel Prize.",
    nameOrigin: "Named after physicist Lise Meitner.",
  },
  {
    atomicNumber: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    atomicMass: 281,
    category: "transition-metal",
    state: "unknown",
    group: 10,
    period: 7,
    xpos: 10,
    ypos: 7,
    funFact:
      "First created in 1994 by fusing nickel and lead nuclei together.",
    nameOrigin: "Named after Darmstadt, Germany, where it was discovered.",
  },
  {
    atomicNumber: 111,
    symbol: "Rg",
    name: "Roentgenium",
    atomicMass: 282,
    category: "transition-metal",
    state: "unknown",
    group: 11,
    period: 7,
    xpos: 11,
    ypos: 7,
    funFact:
      "Sits below gold and silver, but exists only as a few atoms lasting seconds at most.",
    nameOrigin: "Named after Wilhelm Roentgen, discoverer of X-rays.",
  },
  {
    atomicNumber: 112,
    symbol: "Cn",
    name: "Copernicium",
    atomicMass: 285,
    category: "transition-metal",
    state: "unknown",
    group: 12,
    period: 7,
    xpos: 12,
    ypos: 7,
    funFact:
      "Predicted to be so volatile it might be a gas or liquid — a possible 'noble metal' oddity.",
    nameOrigin: "Named after astronomer Nicolaus Copernicus.",
  },
  {
    atomicNumber: 113,
    symbol: "Nh",
    name: "Nihonium",
    atomicMass: 286,
    category: "post-transition-metal",
    state: "unknown",
    group: 13,
    period: 7,
    xpos: 13,
    ypos: 7,
    funFact:
      "The first element discovered in Asia, by Japan's RIKEN lab.",
    nameOrigin: "From 'Nihon', the Japanese name for Japan.",
  },
  {
    atomicNumber: 114,
    symbol: "Fl",
    name: "Flerovium",
    atomicMass: 289,
    category: "post-transition-metal",
    state: "unknown",
    group: 14,
    period: 7,
    xpos: 14,
    ypos: 7,
    funFact:
      "Lies near the theorized 'island of stability' of longer-lived superheavy nuclei.",
    nameOrigin: "Named after the Flerov Laboratory of Nuclear Reactions in Russia.",
  },
  {
    atomicNumber: 115,
    symbol: "Mc",
    name: "Moscovium",
    atomicMass: 290,
    category: "post-transition-metal",
    state: "unknown",
    group: 15,
    period: 7,
    xpos: 15,
    ypos: 7,
    funFact:
      "Confirmed in 2015 and officially named in 2016, alongside three other new elements.",
    nameOrigin: "Named after the Moscow region of Russia.",
  },
  {
    atomicNumber: 116,
    symbol: "Lv",
    name: "Livermorium",
    atomicMass: 293,
    category: "post-transition-metal",
    state: "unknown",
    group: 16,
    period: 7,
    xpos: 16,
    ypos: 7,
    funFact:
      "Made by fusing calcium ions into curium; only a few atoms have ever been detected.",
    nameOrigin: "Named after the Lawrence Livermore National Laboratory.",
  },
  {
    atomicNumber: 117,
    symbol: "Ts",
    name: "Tennessine",
    atomicMass: 294,
    category: "halogen",
    state: "unknown",
    group: 17,
    period: 7,
    xpos: 17,
    ypos: 7,
    funFact:
      "The second-heaviest known element; its name honors the US state that supplied the rare berkelium target.",
    nameOrigin: "Named after the US state of Tennessee.",
  },
  {
    atomicNumber: 118,
    symbol: "Og",
    name: "Oganesson",
    atomicMass: 294,
    category: "noble-gas",
    state: "unknown",
    group: 18,
    period: 7,
    xpos: 18,
    ypos: 7,
    funFact:
      "The heaviest known element; though grouped with the noble gases, it may not be gaseous or inert at all.",
    nameOrigin: "Named after physicist Yuri Oganessian, alive at the time of naming.",
  },
];

export default elements;
